### ISSUE TITLE
Review smartseq2 user documentation

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#102]
Please check for accuracy and completeness so Jodi can improve this. 

SS2:
https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/smart-seq2-workflow-in-detail
Add Benchmarking information if applicable.

QC metrics section:
https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/qc-mertics

**Comment by jodihir** [comment]
Here is the updated link: https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/learn/userguides/secondary-analysis/smart-seq2.md

**Comment by jodihir** [comment]
@jishuxu, a couple of questions:
1. Can you point me to a link or links for the GRCh38 human genome primary sequence?
2. I'm not sure about the Insertion Size part in the QC module explanation
3. Do you have current QC demo data I can link to?

**Comment by jodihir** [comment]
questions answered and jodi is updating the doc
