### ISSUE TITLE
Iterate on Optimus documentation draft

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#103]
https://github.com/HumanCellAtlas/data-portal-content/tree-save/Jodi_10X/learn/userguides/secondary-analysis/10x/10x.md

This needs to be reviewed for accuracy and clarity, and the table has several holes that need to be filled in.

AC:
Overall sections of draft documentation are confirmed by Ambrose
Material for each section exists and are given to Jodi

https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/learn/userguides/secondary-analysis/10x.md

**Comment by ambrosejcarr** [comment]
- Begun updating docs. Pushed a branch with some updates. Still needs links, metrics descriptions, and a workflow graph. 

Diff is here: https://github.com/HumanCellAtlas/data-portal-content/compare/ajc-optimus-docs?expand=1
