### ISSUE TITLE
Update query for new bundle structure and metadata

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#104]
Ingestion is updating the bundle structure, there are examples in the metadata examples github repo for us to work against and blue will let us know when they have bundles ready for us. Metadata also has some new breaking changes, not sure if there are example bundles for this yet.

AC:
SS2 query works with new bundles

Example spreadsheet: https://github.com/HumanCellAtlas/metadata-schema/blob/integration/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx from Mallory

Also from Mallory: There is a new SS2 bundle in the integration DS (`358fa218-9b3e-4b44-8beb-bfa9c4aa7aee`) using the new bundle structure. This bundle is based on ingesting the DCP-wide integration test spreadsheet, which has been updated to the metadata standard in the metadata-schema repo integration branch.

**Comment by samanehsan** [comment]
The SS2 bundle `358fa218-9b3e-4b44-8beb-bfa9c4aa7aee` is no longer in the integration data store. @malloryfreeberg do you know of another bundle we could use that has the newest bundle structure changes? Also did the example spreadsheet move? The link takes me to a 404 page.

**Comment by malloryfreeberg** [comment]
@samanehsan The link should be https://github.com/HumanCellAtlas/metadata-schema/blob/integration/infrastructure_testing_files/dcp_integration_test_metadata_1_SS2_bundle.xlsx I just updated this in the ticket. We moved the current test files to the `/current` directory under `/infrastructure_testing_files`.

**Comment by malloryfreeberg** [comment]
I re-ingested the same spreadsheet in the integration environment and exported a bundle with UUID: `1e276fdd-d885-4a18-b5b8-df33f1347c1a`.  You can see the bundle manifest [here](https://dss.integration.data.humancellatlas.org/v1/bundles/1e276fdd-d885-4a18-b5b8-df33f1347c1a/?replica=aws). 

Were you able to see the previous bundle before, and then suddenly couldn't see it anymore? If so, this is an issue to bring up with the DS. If you never were able to see the bundle by querying the UUID, it's possible that the DS doesn't have indexing working for the new bundle structure yet, and therefore querying for the bundle UUID won't work. You can view the files submitted by ingest by tracing the links in the [bundle manifest](https://dss.integration.data.humancellatlas.org/v1/bundles/1e276fdd-d885-4a18-b5b8-df33f1347c1a/?replica=aws) (e.g. the sequencing_protocol JSON is viewable [here](https://dss.integration.data.humancellatlas.org/v1/files/6a360ede-9388-45f8-8a16-acad53d2388d/?replica=aws). But that won't help much with designing the elastic search queries. 

Sounds like you might be blocked by the DS indexing the new bundle structure, but do let me know if there's something else I can help with :)

**Comment by samanehsan** [comment]
The bundle doesn't come up in the search, so I think it has to do with indexing like you mentioned! Thanks @malloryfreeberg!

**Comment by rexwangcc** [comment]
It seems I can get both `1e276fdd-d885-4a18-b5b8-df33f1347c1a` and `358fa218-9b3e-4b44-8beb-bfa9c4aa7aee` by querying the `/bundles/{uuid}` endpoint of integration DSS right now.

**Comment by rexwangcc** [comment]
Blue's related PR: https://github.com/HumanCellAtlas/data-store/pull/1469

**Comment by samanehsan** [comment]
Here is the PR! https://github.com/HumanCellAtlas/lira/pull/93 

Like Rex mentioned, it's possible to get the bundle manifest using the `/bundles/{uuid}` enpoint but it does not appear in the `search` endpoint results, so we currently can't test that this query works.

**Comment by kbergin** [comment]
So fast!!!! Ok, can someone sync with Brian/blue to see where we're at there?

**Comment by kbergin** [comment]
YAY
