### ISSUE TITLE
Review picard metrics naming for optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#105]
Consider mapping the optimus metrics onto picard and naming them in the same scheme so that users only have one metric name for the same metric across DCP pipelines

AC:
List of metrics to be updated, names to be changed to, conclusion on this effort

**Comment by kbergin** [comment]
@ambrosejcarr were you all set on this ticket? (judging from what you said in the team discussion)

**Comment by ambrosejcarr** [comment]
I'm good on the naming, but the deliverable w.r.t. mapping the names still needs closure.

**Comment by kbergin** [comment]
Got it ok, awesome. Sprint ends Tues if we can get it done by then! :)

**Comment by ambrosejcarr** [comment]
I propose we table this until we have a bit more clarity on 10x v2 development directions.

**Comment by ambrosejcarr** [comment]
RFC: https://github.com/HumanCellAtlas/skylab-analysis/pull/8

**Comment by samanehsan** [comment]
I left some comments, but this ticket still needs a CB reviewer :)

**Comment by ambrosejcarr** [comment]
Proposed Epic: https://docs.google.com/document/d/1h5ak8GL0hlP2T2jctYRpLpawZY7iKWmG-_MYp9Iuhag/edit?usp=sharing

**Comment by kbergin** [comment]
Tickets for this have been put into this epic https://app.zenhub.com/workspace/o/humancellatlas/secondary-analysis/issues/257

**Comment by ambrosejcarr** [comment]
:+1:
