### ISSUE TITLE
Big Red Button

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#108]
As an operator of the DCP, if I suspect abuse or need to accomplish maintenance I need a way to shut down and bring back up each service in the DCP. This is considered required for the go-live. Please see this document for more information, or contact Trent Smith with questions. 

https://docs.google.com/document/d/1eWknDSh2aoDtdBYmSa4Zvp8mTGJWXnKUhcm0aWZBxmI/edit#

Acceptance Criteria:
1) Script that disables the service (without losing data and with a message to users that indicates service being down)
2) Script that enables the service
3) Documentation on how both work
4) Correct people have the permission to run them

Note from comments: We have a command that will shut down new requests already

**Comment by samanehsan** [comment]
PR: https://github.com/HumanCellAtlas/lira/pull/92

**Comment by samanehsan** [comment]
Dave suggested moving the scripts to the secondary-analysis repo, so the new PR is here: https://github.com/HumanCellAtlas/secondary-analysis/pull/243
