### ISSUE TITLE
Runbooks for operations and failure handling

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#113]
Here is the list of failure handling we expect for Green. Some of them require a runbook. We will be making operation docs in the DCP wide operations doc repo (tbd) where these runbooks could also reside. Consider writing them in markdown so they will look nice on github.

https://docs.google.com/spreadsheets/d/1CA2v2dAFAcM-smH6l_MgNxau4JpPbDFiAwN3lYb-SHg/edit#gid=349231869

AC:
Runbook for all pilot phase required failure handling use cases, and operator docs for ones that have other mitigation strategies.

Rhian has made a list for documentation_checklist for operations documentation [here](https://docs.google.com/spreadsheets/d/1YGA34Gp2TiNzPRAaOFHLZ6h1IJA5QStQQKga_6fOOpk/edit)

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-363)

**Comment by rhiananthony** [comment]
This is a Q3 priotity, can we please move this out of the ice box?

**Comment by kbergin** [comment]
Go for it!

**Comment by stahiri** [comment]
@kbergin I've updated the milestones and moved this to Product Backlog, but I'm not sure who the owner should be. Can you advise?

**Comment by kbergin** [comment]
Probably @jkaneria or @rhiananthony

**Comment by stahiri** [comment]
This work has shifted to Q4 as carryover MUST HAVE work. I've updated the release and milestone to reflect this.

**Comment by rhiananthony** [comment]
The objective for Q4 has been met - the runbook exists and documents the procedures for deployment. We're closing this ticket and will open a new one when we address operational runbooks
