### ISSUE TITLE
Get DCP visibility into Green Box

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#133]
After we are on CaaS Prod and have a JMUI on CaaS Prod, we should collect a group of operations users we want to have *read* access to the green box workflows. 

AC:
DCP-Ops has visibility into green via the job manager
Share link to access via API
Runbook /documentation somewhere - I know Bernick was thinking about onboarding/offboarding documentation and I think removing someone from this group would be included in that

Refinement notes
Job manager read access
- [ ] Firecloud accounts with correct permissions
- [ ] Should think about how we want to do grouping
API:
- [ ] CaaS Prod read access through JM API?

*out of scope*
Need service account key to access via code - this is reflected in #81
Longer term we may want to think about scripts to do this

**Comment by samanehsan** [comment]
@rexwangcc made a good point that only mint team members can access cromwell logs in our google bucket, so we would need to add dcp ops members to that as well

**Comment by rexwangcc** [comment]
As a part of this ticket, I have granted the DCP Operations google group `Storage Object Viewer` access to our cromwell-execution bucket on `integration` and `staging` environments.
