### ISSUE TITLE
Review user documentation: QC metrics

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#158]
Please check for accuracy and completeness so Jodi can improve this. You can leave comments on the Google doc or in the Github article, whichever you prefer. Links are:
GIthub: https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/learn/userguides/secondary-analysis/qc-metrics.md
Google doc: https://docs.google.com/document/d/11wMRGGguLxB1Fd4wZgerdWWI-BHjQXAxsw5YXyu5etE/edit

**Comment by jodihir** [comment]
The Google doc: https://docs.google.com/document/d/11wMRGGguLxB1Fd4wZgerdWWI-BHjQXAxsw5YXyu5etE/edit
has a list of metrics I'd compile earlier.  You can check to see if it's correct; if it is, I can just add that to the documentation in the portal, which is here:

https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/qc-mertics
