### ISSUE TITLE
Fix Optimus metrics

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#170]
Optimus metrics depend on properly sorted Bam files (3x tags). Right now, samtools sorts on one tag only, breaking the optimus metrics. 

Once we've implemented functionality in picard which can do hierarchical sorting, we should go back and fix the metrics.

AC:
Tests exist and fail when sorting doesn't work
Tests pass when metrics are correct (bc sorting is correct)

**Comment by kbergin** [comment]
Context from hierarchical bam ticket:
To properly calculate our metrics for optimus, we need to be able to hierarchically sort our bam outputs. Picard has a bam sorting, but it currently cannot do this type of sorting. We would like to update this sorter to sort the bam how we need for Optimus.

Sam tools can currently sort by one tag and then by either coordinate or queryname. We need it to sort by multiple tags and then queryname.

sam tags quick info:
cell barcode - CB
gene barcode - GE
UMI barcode - UB

AC:
Bam sorted by:

cellbarcode > gene barcode > UMI > QueryName
Gene Barcode > UMI > Cell Barcode > Query Name
So that we can calculate cell level QC metrics (1) and gene level QC metrics (2). Currently the count matrix is calculated from a bam sorted by cell barcode and then queryname. We could calculate it using the bam hierarchically sorted like number 1.

**Comment by dshiga** [comment]
We can work on getting support for this in Picard in the longer term. For now, I am going to pursue @ambrosejcarr's idea of just reading the whole bam into memory with pysam and sorting it hierarchically there.

**Comment by dshiga** [comment]
https://github.com/HumanCellAtlas/sctools/pull/46
https://github.com/HumanCellAtlas/skylab/pull/125
