### ISSUE TITLE
Optimus pipeline uses new count matrix improvements

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#173]
In #90 Mehrtash improved a part of sctools that produced a more accurate count matrix. We need to merge using that into Optimus. It relies on a query name sorted Bam. 

AC:
Optimus uses new sctools improvements.
Needs a release, update optimus to use it

**Comment by dshiga** [comment]
I believe this is done, since I updated the optimus pipeline to use the latest sctools (including Mehrtash's changes) when I merged my sorting PR.
