### ISSUE TITLE
Update analysis outputs of SS2

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#183]
Update our adapters to output the new pipeline grouped QC output and bam index output and update to the new SS2 pipeline.

AC:
integration test passes and QC metrics and bam index is output

This will probably break all of our tests.

**Comment by dshiga** [comment]
Consider whether we still need to explicitly list every analysis output or if there is some way to just pass an array of all outputs to the submit wdl (assuming we submit every output and not just a subset). Ideally, in future, adding an output to the analysis wdl won't require us to change the adapter wdl.

**Comment by samanehsan** [comment]
This is unblocked by Jishu's PRs to update the SS2 analysis outputs!

**Comment by samanehsan** [comment]
Here are the PRs:
- https://github.com/HumanCellAtlas/pipeline-tools/pull/72/files
- https://github.com/HumanCellAtlas/lira/pull/99

**Comment by samanehsan** [comment]
These two PRs should not be merged until Jishu's changes to the SS2 pipeline are merged in, but they can still be reviewed! @dshiga approved the Lira PR, and I just need a review for the pipeline-tools one now!

**Comment by samanehsan** [comment]
This PR updates the SS2 outputs in the DCP integration test: https://github.com/HumanCellAtlas/dcp/pull/124
