### ISSUE TITLE
Current pipeline literature review

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#184]
As the community of people running snRNA-seq, I would like the pipeline written to process my data to reflect the best practices determined by the community. A literature review will help us understand what the current state is and help us find a pipeline to benchmark against.

AC:
- [ ] Curate a list of papers to read
- [ ] Read them and summarize key takeaways
- [ ] Understand the work enough to talk to community experts about the pipeline/assay
- [ ] Create list of experts, their institute, and a contact or connection to connect us.

**Comment by jishuxu** [comment]
dropseq:https://www.sciencedirect.com/science/article/pii/S221112471830158X?via%3Dihub
smartseq v4 C1: http://celltypes.brain-map.org/rnaseq
DroNc-seq: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5623139/
STRT-seq-2i(microwell): https://www.nature.com/articles/s41598-017-16546-4

research paper:
breast cancer: https://www.nature.com/articles/s41467-017-00244-w
mouse brain neuron, multiple protocols: https://www.biorxiv.org/content/biorxiv/early/2017/12/25/239749.full.pdf
