### ISSUE TITLE
Update Optimus Query

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#209]
After discussing with @malloryfreeberg and @ambrosejcarr we should modify the 10x subscription query that Lira uses to remove the "dissociation_method" field since it is not relevant to the pipeline.

In addition, we are matching on a text field and it is case sensitive.

In #96 Mallory commented that we could use the ontology term instead of the text field, if we want to.

From elastc:
- Remove the "dissocation_method" field from the query since the 10x pipeline does not rely on that field. 
- Change the "library_construction_approach" term from "10x sequencing" to "10X sequencing" (capitalize the "X") to match the ontology term

AC: 
- Query matches "v6" (newest metadata schema) 10x bundles in the data store

**Comment by dshiga** [comment]
https://github.com/HumanCellAtlas/lira/pull/98
