### ISSUE TITLE
Improve organization of testing code in sctools

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#221]
@samanehsan observed that the testing code could be better organized. However, pytest seems structured to run as functions. If we could find a nice way to organize tests into classes without breaking the fixture functionality, this would be a nice addition to sctools.

AC:
Code is satisfactorily refactored into a better organization, see below for ideas

From @ambrosejcarr

**Comment by ambrosejcarr** [comment]
Having developed more using pytest, my sense is that moving to classes will add unnecessary obfuscation and that separating out the tests into a wider file hierarchy, thus using the file and directory names to organize, is likely a more parsimonious solution.

**Comment by samanehsan** [comment]
That sounds good to me!

**Comment by kbergin** [comment]
Thanks! I changed the name of the title and the AC a bit to reflect the actual goal of this ticket. Implementation can be addressed when it is picked up.
