### ISSUE TITLE
[spike] Pick feature assignment tool

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#229]
Figure out tagging with gene name, location
Choose a custom feature assignment method or DropSeqTools or maybe umitools?
Check if dropseq tools is testing their code

AC:
Analysis
Choose a feature assignment tool

Notes from elastc ticket:
Currently we use dropseqtools ( @ambrosejcarr @mbabadi is that still true?) and this may be fine. There's a possibility for discussion about which assignment tool we want to do. Need to pick aligner first. Not a space of contested scientific innovation.

┆Issue is synchronized with this [Jira Bug](https://broadinstitute.atlassian.net/browse/GL-513)

**Comment by ambrosejcarr** [comment]
> Currently we use dropseqtools ( @ambrosejcarr @mbabadi is that still true?)

Yes.
