### ISSUE TITLE
Get DCP ops firecloud accounts

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#237]
To enable visibility into the green box we want to give all of DCP operations access to see our workflows running in our execution engine. To gain access, our permissions service SAM currently requires users to make a account through our app Firecloud. Please make an account following the instructions below, check yourself off the list, and add the email you used to make the account in a comment. We will then give you the correct permissions and links to see the workflows running through analysis.

To create a firecloud account, go to [https://portal.firecloud.org/](https://portal.firecloud.org/), click "sign in with google" and fill out the new user registration form. 

- [ ] Andrey 
- [x] Brian H.
- [ ] Calvin
- [ ] Kevin O.
- [x] Madison
- [x] Matt W. 
- [x] Parth 
- [x] Sam P.
- [x] Trent
- [x] Alegria
- [ ] Hannes
- [ ] Mallory
- [ ] Norman
- [x] Rodrey
- [ ] Rolando
- [ ] Simon 
- [ ] Tony

**Comment by parthshahva** [comment]
Email used: pshah@chanzuckerberg.com

**Comment by aaclan-ebi** [comment]
Email used: aaclan@ebi.ac.uk

**Comment by kbergin** [comment]
kbergin@broadinstitute.org

**Comment by sampierson** [comment]
spierson@chanzuckerberg.com

**Comment by rdgoite** [comment]
rodrey@ebi.ac.uk

**Comment by kbergin** [comment]
When other folks ask to be added to the DCP ops firecloud group we'll add them, anyone on Mint can add them.

**Comment by samanehsan** [comment]
And a note for those on the mint team, here are the firecloud groups that we're using for our integration and staging environments to give people read-access:
- mint-test-read-access
- mint-staging-read-access

**Comment by kislyuk** [comment]
Email used: akislyuk@chanzuckerberg.com

**Comment by justincc** [comment]
justincc@ebi.ac.uk

**Comment by prabh-t** [comment]
prabhat@ebi.ac.uk

**Comment by ESapenaVentura** [comment]
enrique@ebi.ac.uk

**Comment by mshadbolt** [comment]
mshadbolt@ebi.ac.uk

**Comment by ESapenaVentura** [comment]
It's not working for @mshadbolt or me @samanehsan

**Comment by mshadbolt** [comment]
We figured it out. There's an extra 'register' step that isn't so intuitive...
