### ISSUE TITLE
Analysis on reference masking multi-mapping overlap

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#238]
An additional analysis to identify the types of multi mapping and where it is shared.

From Tim: 
> A question I have is where multi-mapping is shared. So given the biotypes of interest (say mRNA, lincRNA, and anti-sense RNA that you identify as important here) take all the reads that multiple to one of those, say mRNA, and plot what other biotypes are also sharing those multi-mappings. (Do this separately for each of the important biotypes). This will help answer the question if we would recover more signal from unimportant biotypes if they are excluded.

From Ambrose:
> Identifying points of overlap is key. If it's mostly protein-coding overlapping other protein coding, then that is not addressable by masking. This is the next thing to be done here, I think.

AC:
Addition of these analysis results to the [doc on reference masking](https://docs.google.com/document/d/16ltrY2UfgJHwMzFZtGKIafP4cU2m_Pa-Z9yQaxzaOrM/edit#)

┆Issue is synchronized with this [Jira Bug](https://broadinstitute.atlassian.net/browse/GL-516)

**Comment by ambrosejcarr** [comment]
From Tim: 
> If we feel that short and not polyA reads are basically random or artifact, would it be helpful to align to those biotypes and see if the rate of alignment is more than the intron alignment rate. Or something close to this. I like that enrichment should biological functionality is not potentially interesting. I wonder if it is also helpful to answer if the alignment rate in those "masked" spaces align at a rate that is noise and are not pile-ups. That would really close the case for me.
