### ISSUE TITLE
Help get SS2 and Benchmarking into Unity

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#242]
So that we can do benchmarking in Unity, we need to ensure our pipeline is public and runnable in Firecloud, both the SS2 and Benchmarking pipelines. 

- [x]  Dockers have credentials fixed - need to be able to run the docker images
- [x] Benchmarking inputs in a public bucket
- [x] Help running the benchmarking wdl in Firecloud, may need some changes to WDL itself.
- [ ] Make demo-ready wdl that runs both the pipeline and the benchmarking with the hard-coded 'pipeline A' inputs, which are in a public bucket
- [ ] Make testing data (96 cells) and put in public bucket
- [ ] Stretch: Upload to firecloud

Not merged into our repos and will be updated later to match what we will actually do in HCA (using loom as output format, etc)

**Comment by jishuxu** [comment]
PR: https://github.com/HumanCellAtlas/skylab/pull/123
