### ISSUE TITLE
Get cellranger wdl dcp ready

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#245]
In an effort to 1) make sure Optimus can get into production as quickly as possible when ready and 2) de-risk the November launch in case Optimus gets delayed, we have decided to enable the green box to run a simple 10x wrapped pipeline. This will serve as a test of the plumbing of the DCP to handle 10x data because it will be incorporated into the dcp wide integration test.

The majority of the work has been done as this pipeline already exists in the single cell portal and has been tested with some smaller data by @mbabadi (please get this data from him)

The work to test this pipeline in the green box is split into separate tickets. This ticket represents work like: updating the WDL to use DCP approved/mint approved docker images, updating any requirements about subworkflows and parameter/meta blocks, naming of inputs/outputs to work for us, and putting it in skylab. Anything remaining to make the analysis wdl itself ready to run in the DCP.

Ambrose notes that there are a lot of outputs so it may not be worth renaming them, but balance this decision with the effort required to change the adapter wdl when we do pull in optimus.
Building the permissive license from github in docker may be a bit of effort (latest cellranger)

AC:
- [ ] analysis wdl checked into skylab

**Comment by dshiga** [comment]
@TimothyTickle or @bistline, do you know where we can get a copy of the cellranger WDL, which I understand is currently used in the single cell portal?

**Comment by dshiga** [comment]
Tim pointed me to it here: https://portal.firecloud.org/#methods/single-cell-portal/cellranger_count/1/wdl

**Comment by bistline** [comment]
There is also this: https://portal.firecloud.org/#methods/single-cell-portal/cell-ranger-2-0-2/10

That's v2.0.2 - the one Tim pointed you to is v2.1 or v2.2, I believe.
