### ISSUE TITLE
Add 10x to DCP integration test

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#248]
In an effort to 1) make sure Optimus can get into production as quickly as possible when ready and 2) de-risk the November launch in case Optimus gets delayed, we have decided to enabling the green box to run a simple 10x wrapped pipeline. This will serve as a test of the plumbing of the DCP to handle 10x data because it will be incorporated into the dcp wide integration test.

When 10x is running in green box, use the plumbing test sized data that @mbabadi has to add the 10x pipeline to the DCP integration test.

AC:
10x is running in DCP integration test

**Comment by kbergin** [comment]
This could be relevant here: https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/107

**Comment by samanehsan** [comment]
After the promotion from int --> staging this week, we'll need to update gitlab to run the 10x pipeline test in staging: https://github.com/HumanCellAtlas/dcp/blob/integration/.gitlab-ci.yml#L30
