### ISSUE TITLE
Add 10x pipeline to mintegration test

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#255]
When 10x is running in green box, use the plumbing test sized data that @mbabadi has to add the 10x pipeline to the DCP integration test.

Needs a bundle for mintegration test with test data in it. 

AC:
10x pipeline is in mintegration test and passes

**Comment by kbergin** [comment]
This could be relevant here: https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/107

**Comment by samanehsan** [comment]
PR for review: https://github.com/HumanCellAtlas/secondary-analysis/pull/367
