### ISSUE TITLE
Update adapters for new bundle structure

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#256]
See #104 for more context. 

AC:
adapters and analysis json are updated
mintegration and integration test is passing

**Comment by dshiga** [comment]
Consider making use of the new metadata-api library to simplify this code and insulate us from future changes: https://github.com/HumanCellAtlas/metadata-api/blob/master/src/humancellatlas/data/metadata/__init__.py

**Comment by kbergin** [comment]
Oh awesome that that exists, is that stable enough/tested enough for us to use? Can whoever picks this up check with Hannes on that? @dshiga

**Comment by hannes-ucsc** [comment]
I just released the [alpha 4 of the metadata-api](https://github.com/HumanCellAtlas/metadata-api/tree/release/1.0a4). It supports both the old and new bundle structure. Most of the metadata fields exposed by the API are for Orange but there is one accessor that we added specifically with Green in mind: [Bundle.sequencing_input](https://github.com/HumanCellAtlas/metadata-api/blob/release/1.0a4/src/humancellatlas/data/metadata/__init__.py#L571). Let me know if you see the need for exposing additional properties or accessors.
