### ISSUE TITLE
Update where we get our pipeline version from

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#262]
Currently we are hitting cromwell API to get our workflow version from the metadata labels, but we want to use as a workflow output from the analysis pipeline itself instead, as it gives us fewer dependencies. Updating this requires an update to the tagged version of the pipeline, an update to the expected outputs for the PR test for skylab, and an update to the adapter wdls. 

Dependencies that use the SS2 pipeline like the benchmarking pipeline may need to be updated as well, unless they don't use all the outputs of the wdl. 

AC:
Our pipeline version is not pulled from cromwell
Re-deployed green box with new version of pipeline

**Comment by rexwangcc** [comment]
Merged!

**Comment by rexwangcc** [comment]
We don't want to use this version (v0.29.0) of pipeline-tools in either integration or staging until we have a tagged version of SS2 pipeline!
