### ISSUE TITLE
Cromwell tools refactor and testing

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#276]
There is a PR that requires changes to other services to accommodate the changes, and needs more tests. Create the update the automated tests for this package.

AC:
Enough tests to merge this PR;
https://github.com/broadinstitute/cromwell-tools/pull/31
~Update Lira, Falcon, Pipeline tools, mintegration test to use updated code~ Separated to #333
~Update test cases~ Improving test cases is now separated to #387

^ Is this too much for one ticket?

**Comment by rexwangcc** [comment]
Closing with https://github.com/broadinstitute/cromwell-tools/pull/43
