### ISSUE TITLE
Refactor falcon deployment scripts

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#277]
Falcon deployment scripts aren't set up in the same way as the lira ones now are and won't be as easy to hookup into gitlab when we do this move. There is a need to refactor to match.

AC:
Falcon deployment scripts are hooked up into gitlab

**Comment by samanehsan** [comment]
I opened a few issues in the secondary-analysis-deploy repo with some code-review comments
