### ISSUE TITLE
v2 cromwell backend update

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#279]
Research any effects this may have and complete the migration for our dev Cromwell. This will help us for testing and will reassure us that when CaaS updates our workflows will succeed.

Henry put in the functionality for CaaS to support v2 backend. They recommend using the workflow option to set it up to do v2 and test all our workflows. After all our workflows succeed, we should let Henry know that the backend default can be v2 now.

DEADLINE for moving to v2 is December 31! Let Ruchi/Henry know if we hit blockers.

Ruchi will send our SS2 workflow to google to test

Adding the following to options of the workflows will make them use v2 backend:
```
"backend": "PAPIv2" 
```

**Comment by rexwangcc** [comment]
We have seen s et of new errors with PAPI v2, need to check in with @hjfbynara

**Comment by samanehsan** [comment]
Since we're using PAPI v2 now, should we close this ticket and possible create a new one for testing with PAPI v2 and/or tracking the errors?

**Comment by rexwangcc** [comment]
+1 for ⬆️

**Comment by rexwangcc** [comment]
Also, note that we are currently only using papi v2 in `integration` on a feature branch: https://pipelines.integration.data.humancellatlas.org/version

**Comment by samanehsan** [comment]
Oh I see! Wow I totally missed the first line of this ticket which already says `Research any effects this may have and complete the migration for our dev Cromwell. ` 😆

**Comment by rexwangcc** [comment]
Well, I'd say I missed that too 😆

**Comment by kbergin** [comment]
I think in refinement it was a suggestion that we try this in our dev cromwell first to see if it worked ok for us. I think we went a different route, and that's fine too. I'm open to splitting the tickets however you'd like. But let's at least provide some concrete update to consider this ticket done, just because I'd like a bit more context. i.e. a summary on the tests we've run so far and their error rate, a link to a tracking sheet with the errors, and (if we have it) a decision on whether we can move to papi v2 for now without issue or if we need to continue testing/monitoring before we are comfortable.

**Comment by samanehsan** [comment]
I just checked that all of our environments are using PAPIv2 as the backend, so I think we can close this ticket now @kbergin!
