### ISSUE TITLE
Harmonize Pipeline-tools dependencies

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#283]
We got a warning: `DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release. warning` in pipeline-tools.

Currently pipeline-tools is using the `dependency_links` within the `setup.py`, and the image is using `RUN pip install . --process-dependency-links --trusted-host github.com` to install the package within the docker image. We need to address this problem before they fully deprecate the dependency links.

AC:
1. Find another way to process the dependencies within `setup.py`.
2. Choose either `requirements.txt` or `setup.py` and stick with it in the future. (Since pipeline-tools is more like a library than a service, we might want to prefer using`setup.py`)
3. If possible, we should think about publishing cromwell-tools and pipeline-tools on PyPi from a specific version.

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-400)

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

We are no longer using the dependency links in setup.py so I would consider this complete: https://github.com/HumanCellAtlas/pipeline-tools/blob/master/setup.py#L27 ( https://github.com/HumanCellAtlas/pipeline-tools/blob/master/setup.py#L27|smart-link )
