### ISSUE TITLE
Improve the way we get metadata files in `pipeline_tools.input_utils`

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#284]
Currently `pipeline_tools.input_utils` is using our own `HttpRquests` class with a special retry policy to send requests to Blue and fetch metadata files one by one. In order to speed up the input processing time and also adapt to Data-Store's standards, we might want to:

1. Adopt `dss_client` and modify our `HttpRequests` class.
2. @dshiga mentioned there is a way to download all metadata files at once using `/serach` endpoint of DSS, we should use it if it's possible.

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-401)

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

We are now using a function from the metadata api library that downloads bundle metadata from the data store and uses the DSS client. The search endpoint will be depricated in favor of the query service so that is not feasible for us to use.
