### ISSUE TITLE
Create read groups for DCP ops access to Green Box envs

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#285]
AC:
Create a read only group in int and staging
Add dcp ops folks to the read group access 
Test that it's working as expected

Check about prod, or maybe do it later?

**Comment by samanehsan** [comment]
Done for integration and staging!

**Comment by samanehsan** [comment]
Also done for prod!

**Comment by samanehsan** [comment]
Mint team members are admins on these groups, which are all listed out in https://portal.firecloud.org/#groups
