### ISSUE TITLE
Update outputs of Optimus to zarr

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#288]
As a first step towards being able to work with the matrix service and having a coordinated QC metric library. Dump qc metrics from sctools into zarr and change count matrix output to zarr format. 

As a user of the Optimus pipeline outside of the DCP infrastructure, I may not want to use zarr as my output format. The conversion of the outputs to zarr should thus be an optional feature.

AC:
- [ ] Need a deprecation warning in the top of our metrics output about it changing soon after closed beta - Recommendation from Ambrose, talk to him if you want to argue implementation details: Use the zattrs field to include a deprecation warning that the schema of the QC metrics to change (the QC metrics names will change to be consistent across pipelines).
- [ ] Include in the attributes information on how the output was produced (like in the top of a bam header)
- [ ] Conversion to zarr is optional
- [ ] Update Optimus pipeline outputs
- [ ] Cut new version of Optimus

**Comment by kbergin** [comment]
Hi @kishorikonwar Can you please check off the ACs if they are accomplished? And @mckinsel as reviewer, can you confirm those ACs are met?

**Comment by kishorikonwar** [comment]
Sure.
