### ISSUE TITLE
Create GitLab Runner

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#294]
We need to stand up a GitLab runner which will be capable of running the jobs that we create in GitLab. We will need one in the dev environment and one in the production environment, each will connect to a their respective GitLab masters.

**Comment by rhiananthony** [comment]
I'll check with Brian to verify that the prod GitLab is set up

**Comment by rhiananthony** [comment]
Prod GitLab is set up and I now have access. I also am on the suitability roster now and am unblocked to begin the move from our jenkins server to the GitLab server
