### ISSUE TITLE
Look into long running analysis workflows

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#302]
At the scale testing F2F we observed some very long running workflows that were A) getting stuck running a particular task, and then getting B) pre-empted and taking even longer to run. We noticed this particularly often with Hisat2, but once with RSEM as well. As an example, most workflows ran for 40min - 1.5 hours and some workflows that got stuck like this did eventually complete on their own but took over 3 hours to run. We did up the memory on a branch to try and see if that fixed it. We suspect it helped with the tasks that got stuck on collectmultiplemetrics as we realized that task was setting memory in the java command hardcoded and that was hitting that memory limit.

We also tried updating the memory for hisat2, but didn't actually observe it using all of the original memory and don't suspect that helped. We should spend more time digging into these long running workflows. 

AC:
- An understanding of why they are taking longer (is it data size or something else?)
- Any follow up tickets to fix the issue are created

┆Issue is synchronized with this [Jira Bug](https://broadinstitute.atlassian.net/browse/GL-528)

**Comment by dshiga** [comment]
Seeing exit status 137 (indicating out of memory) in HISAT2PairedEnd.log for some jobs, for example for attempt 2 of workflow be393d27-f2b9-492b-a007-e44f7cb8b32a.

**Comment by dshiga** [comment]
RSEMExpression had two attempts in this workflow - the first seems to have taken more than an hour: 1ed1af7f-7796-4ba0-b603-95c8915e83d8. This could be a memory thing.
