### ISSUE TITLE
Spike: Docker image for cromwell-metadata credentials pains

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#312]
In retro 9/18 it came up that we need to revisit our strategy for accessing our cromwell metadata credentials as it becomes cumbersome to keep up to date when we make changes in pipeline tools. There wasn't a clear method for making this easier and it was suggested to talk to devops

AC:
Either a plan to fix this with a new ticket created or a fix if it's simple enough.

From notes of DCP F2F in Sept
> Idea about a microservice for accessing metadata that has read only access to cromwell and can be called in the workflow by pipeline tools. Enables us to have more metadata on the workflow or update the labels on a workflow as it is running without storing credentials in a docker image.

**Comment by samanehsan** [comment]
Here is the spike doc: https://docs.google.com/document/d/1DlaZlQaL0pKhGQiXkPHBFfhTZFYN5aNMdzEsfoM4pv8/edit

**Comment by samanehsan** [comment]
@rexwangcc @rhiananthony I updated the notes at the end of the document around Cromwell-support after chatting with Ruchi

**Comment by samanehsan** [comment]
After meeting to discuss the options presented in this spike document, the consensus was to investigate/meet to further discuss option 5a (accessing credentials in the Cromwell VM), otherwise go with option 4 (making a request to get metadata through a proxy service/endpoint).

**Comment by samanehsan** [comment]
Based on further discussion on this spike doc, we will go with the approach outlined in this ticket: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/450
