### ISSUE TITLE
Create Optimus QC Metrics Documentation in Data Portal

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#327]
From Jodi:
QC Metrics page: add need a table about Optimus QC metrics similar to the one for Smart-Seq2:
https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/qc-mertics

Ambrose has documented the metrics in the code and that can be a starting point for the metrics documentation for Optimus.

**Comment by jodihir** [comment]
Will review initially with Tim

**Comment by jodihir** [comment]
@ambrosejcarr Definitions for the cell-specific and gene-specific metrics (https://sctools.readthedocs.io/en/cw-add-readthedocs-hooks/sctools.metrics.html) don't have anchors, so I can't make specific links to them in my QC metrics table (as was done for all the other metrics in the Metric Aggregator Base Class, where there are anchors). If you or someone can make the anchors in the readthedoc at some point I will add them to the documentation.

**Comment by ambrosejcarr** [comment]
I believe I identified the problem, which is explained here: https://github.com/HumanCellAtlas/sctools/pull/49

Unfortunately, our docs have been broken for about 5 months. Rex and I are investigating and will hopefully have a fix soon.

**Comment by jodihir** [comment]
links to metrics definitions updated
