### ISSUE TITLE
Determine how to filter gencode for Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#338]
10X cellranger and Optimus do not function well with overlapping gene regions in a gene annotation. Gencode has these, and it's possible ensembl does too. When 10x creates it's reference with ensembl it creates certain output files that have filtered out these multiple gene annotations. We need to determine how to filter the gencode annotation for Optimus in a way that it will work for Optimus.  10X has information on creating custom references [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references) that mentions using Gencode. They also have information on creating a reference using gencode [here](https://support.10xgenomics.com/single-cell-dna/software/pipelines/latest/advanced/references).

The standard instructions on creating a 10x reference are [here](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#grch38_1-2-0).

A note from @mbabadi : 
>perhaps run `cellranger mkref` on GENCODE v27 according to 10x [recipe](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#grch38_1-2-0), and compare the created ref bundle from the one that is shipped? should be easier than comparing GTF files. like total number of records, total number of genes.

AC:
We have a gencode based reference that works with Optimus. It is likely this reference would also work with cellranger. The metric in question is `Reads Mapped Confidently to Genome` in 10x outputs and `reads_mapped_uniquely` in our Optimus outputs. 

For `Reads Mapped Confidently to Genome` we expect it to be around 67.10%.
`reads_mapped_uniquely` is calculated when the NH tag on a read (number of hits, comes out of STAR) = 1. We also have an Optimus metric `reads_mapped_multiple` which is calculated using the same tag, when it is greater than 1.

**Comment by jishuxu** [comment]
From our latest observation: with and without gene filtering, gencode reference produce consist low in `Reads Mapped Confidently to Genome`.  it indicates that the low in `Reads Mapped Confidently to Genome` might be caused by something we did not know yet.
