### ISSUE TITLE
Make a Green grafana dashboard for all environments

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#339]
We need to work on refining this - what do we want to see on this dashboard.

See this DCP [ticket](https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/66) for more information

AC:
~- [ ] No additional work on improving what is on the dashboard, just standing up what we already had in other environments (again) and then standing up the prod one as well.~
- [x] We have a prod grafana dashboard in prep for cBeta
- [x] Moved to dcp-monitoring, check if Matt can recover our old dashboards

- [x] Dev
    - [x] Lira notification counts
    - [x] Falcon logging pace
    - [x] CaaS prod status
- [x] Integration
    - [x] Lira notification counts
    - [x] Falcon logging pace
    - [x] CaaS prod status
- [x] Staging
    - [x] Lira notification counts
    - [x] Falcon logging pace
    - [x] CaaS prod status
- [x] Prod
    - [x] Lira notification counts
    - [x] Falcon logging pace
    - [x] CaaS prod status

**Comment by mweiden** [comment]
If you pair with me on this, it won't take too long. Maybe half a day. I can also show you how to template and generate dashboards for all your deployments with [dcp-monitoring](https://github.com/HumanCellAtlas/dcp-monitoring).

**Comment by kbergin** [comment]
Thank you @mweiden !

**Comment by rexwangcc** [comment]
PRs are here: 
- https://github.com/HumanCellAtlas/secondary-analysis/pull/445
- https://github.com/HumanCellAtlas/dcp-monitoring/pull/10

Dashboard is here: https://metrics.dev.data.humancellatlas.org/d/qqO9c9Bmz/analysis-staging?orgId=1&from=now-1h&to=now

**Comment by rexwangcc** [comment]
This ticket is done!

**Comment by mweiden** [comment]
@rexwangcc great job Rex!
