### ISSUE TITLE
Prod Health Check notifications for cBeta

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#346]
From the ticket in DCP:
> Every service should have an endpoint which can be pinged and returns an HTTPS 200 status code if the application is running and a non 200 status code if the application is not. This can be at a "/" location, but preferably will be a "/status" or "/health" endpoint.

> Either CloudWatch or Pingdom should be used to check that these endpoints are showing a healthy state and alerts should be built to notify the team when any service is showing a non healthy state.

AFAIK we currently have this for Lira in our other environments and would like to have it set up with CloudWatch or Pingdom for our Prod env. 

AC:
Lira health endpoint is checked and we get notifications for all environments

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-414)

**Comment by rexwangcc** [comment]
I think we already have the `/health` for both Lira and Job Manager, my question is if we want to make Lira's endpoint more sophisticated(means Lira's health endpoint will be responsible for checking the state of Cromwell and then do a **AND** between Cromwell health and Lira's health)?

**Comment by kbergin** [comment]
I think so too, I think the thing we didn't have yet (and is part of this ticket) is connecting it to cloudwatch/pingdom? or maybe it was just that we didn't have it for our `prod` env yet?

If Cromwell is down, I do think I would consider Lira down as well. Wouldn't our notifications just get lost if this were the situation? What is our backup plan there? @rexwangcc

**Comment by rhiananthony** [comment]
I think having lira be responsible for cromwell health is problematic. It will be more complex than necessary and may end up requiring multiple refactorings depending on whether cromwell is changed. At present I would call this ticket "almost" done. I would rather see an endpoint be implemented for falcon.

**Comment by kbergin** [comment]
I'm updating the description of this ticket to represent the specific scope we discussed yesterday. #370 and #371 represent the rest of the discussed work.

**Comment by mweiden** [comment]
@jkaneria  @rexwangcc as far as I can tell from the AC on this ticket, the work is complete. We do have an alert for pipelines in `dcp-monitoring` https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/terraform/modules/env-health-checks/analysis.tf and tickets https://github.com/HumanCellAtlas/secondary-analysis/issues/587 https://github.com/HumanCellAtlas/secondary-analysis/issues/370 https://github.com/HumanCellAtlas/secondary-analysis/issues/371 to cover "L2" health checks.

Can we close this one and deduplicate the others?

**Comment by samanehsan** [comment]
That sounds reasonable to me @mweiden!
