### ISSUE TITLE
[Cont] Determine how to filter gencode for Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#348]
10X cellranger and Optimus do not function well with overlapping gene regions in a gene annotation. Gencode has these, and it's possible ensembl does too. When 10x creates it's reference with ensembl it creates certain output files that have filtered out these multiple gene annotations. We need to determine how to filter the gencode annotation for Optimus in a way that it will work for Optimus.  10X has information on creating custom references [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references) that mentions using Gencode. They also have information on creating a reference using gencode [here](https://support.10xgenomics.com/single-cell-dna/software/pipelines/latest/advanced/references).

The standard instructions on creating a 10x reference are [here](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#grch38_1-2-0).

A note from @mbabadi : 
>perhaps run `cellranger mkref` on GENCODE v27 according to 10x [recipe](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#grch38_1-2-0), and compare the created ref bundle from the one that is shipped? should be easier than comparing GTF files. like total number of records, total number of genes.

AC:
- [x] Comparison report of Optimus full dataset run with gencode vs run with ensembl
- [x] We have a gencode based reference that works with Optimus. The metric in question is `Reads Mapped Confidently to Genome` in 10x outputs and `reads_mapped_uniquely` in our Optimus outputs. 

For `Reads Mapped Confidently to Genome` we expect it to be around 67.10%.
`reads_mapped_uniquely` is calculated when the NH tag on a read (number of hits, comes out of STAR) = 1. We also have an Optimus metric `reads_mapped_multiple` which is calculated using the same tag, when it is greater than 1.

**Comment by kbergin** [comment]
Thus far, we have changed the attribute name using the same name as Ensembl. Then we can run it through cellranger. The summary of the alignment looks very close with that change (0.1% difference). 

- [ ] Did not check count matrices yet, will need to check that.
- [ ] cellranger wdl to make gencode reference needs review

For optimus, use ensembl and gencode ref made by cellranger, and that has run through. Plumbing works, need to analyze.

**Comment by kbergin** [comment]
I'll separate into two tickets

3 points to each

**Comment by kbergin** [comment]
A doc with plans for this from @jishuxu https://docs.google.com/document/d/1F3owOqc3B0gp4hnf9nHydCxVUdtfZKDmnKRoyP_lHhc/edit?ts=5bbcddd9

**Comment by jishuxu** [comment]
https://docs.google.com/document/d/1deQsFltjczv-kN7PuzKHn9xrDQwE07fM7NG3owf-wfA/edit#
