### ISSUE TITLE
Consolidate common optimus/cellranger adapter code 

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#355]
Instead of repeating the same task to get 10x inputs from the data store, move the task into a separate WDL file that can be re-used in the Optimus and Cellranger pipelines. Additionally, the task to format the inputs for the submission WDL can be generalized to work with either pipeline.

AC:
- [ ] Adapter code is refactored for optimus and cellranger

**Comment by kbergin** [comment]
As we do not plan to continue to support Cellranger in the future, we would not like to consolidate this code. Consolidating them would cause us to have to worry about both in the future when we update the code.
