### ISSUE TITLE
SS2 query not restricting to plate-based

### ISSUE THREAD

**Issue by dshiga** [HumanCellAtlas/secondary-analysis#362]
We were attempting to trigger only on bundles using FACS or mouth pipette. However, it turns out that the "should" clause that we use for this does not filter anything out.

This was a surprise to us, but the Elasticsearch documentation clearly states that "should" behaves this way: "If the bool query is in a query context and has a must or filter clause then a document will match the bool query *even if none of the should queries match*."

We should rewrite the query in a way that does require a match on these fields. There has also been discussion in slack about the right way to query -- the FACS / mouth pipette parameters were meant to restrict to plate-based sequencing, however, there is some question about whether using FACS/mouth pipette will accomplish that.

@malloryfreeberg tagging you since you were involved in the slack discussion.

___

The goal here is to make a SS2 query that matches our requirements for our pipelines. The pipeline requires human, smartseq2, paired-end, and plate-based data and should be launched when all of those criteria are met. As Dave mentioned, the FACS and mouth-pipette choices were to restrict to plate based, but it doesn't seem that is working how it should.

AC:
A SS2 query that only matches the above bundles. Please coordinate with Mallory/metadata team to figure out the best way to query for plate-based data.

Note: The other type of data is fluidigm based, which our pipeline doesn't support currently.

**Comment by kbergin** [comment]
Query is currently more permissive than it should be, but none of the closed beta datasets that will match it violate the assumptions our pipelines make, so we will prioritize this after the closed Beta.

**Comment by dshiga** [comment]
For future reference, moving the `should` under a `filter` clause causes it to be enforced. (However these dissociation fields are probably still not the right way to restrict to plate-based, which is the real goal.)
```
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "files.library_preparation_protocol_json.library_construction_approach.text": "Smart-seq2"

          }
        },
        {
          "match": {
            "files.sequencing_protocol_json.paired_end": true
          }
        },
        {
          "match": {
            "files.donor_organism_json.biomaterial_core.ncbi_taxon_id": 9606
          }
        }
      ],
      "filter": {
        "bool": {
          "should": [
            {
              "match": {
                "files.dissociation_protocol_json.dissociation_method.text": "fluorescence-activated cell sorting"
              }
            },
            {
              "match": {
                "files.dissociation_protocol_json.dissociation_method.text": "asdf"
              }
            }
          ]
        }
      },
      "must_not": [
        {
          "match": {
            "files.analysis_process_json.process_type.text": "analysis"
          }
        }, 
        {
          "range": {
            "files.donor_organism_json.biomaterial_core.ncbi_taxon_id": {
              "lt": 9606
            }
          }
        },
        {
          "range": {
            "files.donor_organism_json.biomaterial_core.ncbi_taxon_id": {
              "gt": 9606
            }
          }
        }
      ]
    }
  }
}
```
