### ISSUE TITLE
Update Optimus Adapters for Primetime

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#368]
It has been a long time since we have run Optimus in the DCP. We think there is work to do to update the adapters. After we update Optimus to have zarr outputs, we should update it so we can run the pipeline in the DCP.

~Consider #355 when doing this ticket, they can be kept separate if the work is too much for one ticket.~

AC:
- [ ] Update adapters to support latest tagged version of Optimus
- [ ] Update lira config
- [ ] Zarr output is created, and is captured in adapters
- [ ] Run with current existing dataset to help determine next steps for testing.

**Comment by rexwangcc** [comment]
PRs:
- https://github.com/HumanCellAtlas/pipeline-tools/pull/116

**Comment by rexwangcc** [comment]
Closed by:
- https://github.com/HumanCellAtlas/pipeline-tools/pull/116
- https://github.com/HumanCellAtlas/secondary-analysis-deploy/pull/52
