### ISSUE TITLE
Health endpoint for Falcon

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#370]
We would like to have a single status representing the overall health of the secondary analysis service in the context of the HCA DCP. To do this, we want to be able to ping the health points of all of our services. Thus, we need a health endpoint on falcon. 

Please keep in mind reusability of falcon when choosing an implementation method.

AC:
- [ ] Falcon has a health endpoint we can hit to understand the health of Falcon

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-416)

**Comment by jkaneria** [comment]
Closing this issue to de-duplicate efforts in 371 & 587.
