### ISSUE TITLE
Summary health endpoint and notifications for secondary analysis service in HCA DCP

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#371]
After all of our services have a health endpoint, we'd like to get a single representative health status for the green box in the HCA DCP to deliver to the DCP health dashboards and to put into cloudwatch or pingdom to get notifications when things are down. We'd like this to summarize lira, falcon, and cromwell status (i.e. anything that would notify us that things aren't working as they should be)

Extra question - should we be checking the health of our subscriptions in our health check? Is that a thing?

AC:
- [ ] Infrastructure to determine overall health of green box implemented
- [ ] exposed in dashboard for *all environments*
- [ ] documentation on how it works (that could be user facing so someone else could do it if they reused the system?)
- [ ] connected to health notification system we have chosen to use

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-417)

**Comment by mweiden** [comment]
This work has been started and can easily extended:

* Health check file - https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/terraform/modules/env-health-checks/analysis.tf
* Alerts file - https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/terraform/modules/env-alerts/analysis.tf

**Comment by jkaneria** [comment]
Closing this ticket as a de-duplication of this 371 & 370.
