### ISSUE TITLE
Unique-ify the cellranger outputs

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#372]
It turns out the data store is overwriting the outputs we create from our 10x pipeline because the final files coming out of cellranger have the same names but different directory structures, which blue box ignores. We need to rename the standard output files of cellranger manually to make sure they are kept unique.

AC:
All outputs of 10x that we want to be stored in the data store are stored in the data store

**Comment by samanehsan** [comment]
Here's the PR! https://github.com/HumanCellAtlas/pipeline-tools/pull/90
