### ISSUE TITLE
Timeout while pulling images from quay.io

### ISSUE THREAD

**Issue by dshiga** [HumanCellAtlas/secondary-analysis#373]
We saw 10 workflows fail today while trying to pull images from quay.io:

2018/10/12 14:03:00 W: "docker --config /tmp/.docker/ pull quay.io/humancellatlas/secondary-analysis-rsem@sha256:fd3cd49b51aa082ad253d6bc959d60be58f51f61dae76ddc239013a1258f47fa" failed: exit status 1: Error response from daemon: Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

See this workflow for example: 8acedd7a-9fef-4315-ad6b-7469de8441b0

We might want to consider copying images to gcr and updating WDLs to point there instead. We have a google project hca-dcp-pipeline-images available for that purpose.

We would need to grant access for all our various environments to read from there, or else make the images public:
https://stackoverflow.com/questions/33792803/how-do-i-create-a-public-image-in-google-container-registry-gcr

**Comment by kbergin** [comment]
Copying the content of this ticket to another related issue and closing this ticket.
