### ISSUE TITLE
Fix auto docs build on readthedocs for sctools

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#377]
The auto-build trigger for sctools is broken(for the past few months), we have to fix this ASAP. _Because our autodocs are used to populate a read the docs page for users of sctools and are used by Jodi to create her user documentation. New docs written in the last few months have not been published anywhere outside the code. -Kylee_
For details, see: https://github.com/HumanCellAtlas/sctools/issues/52

AC:
1. sctools docs can appear on readthedocs

**Comment by kbergin** [comment]
Thanks for making this ticket, Rex!

**Comment by rexwangcc** [comment]
PRs:
- https://github.com/HumanCellAtlas/sctools/pull/53
- https://github.com/HumanCellAtlas/sctools/pull/51
- https://github.com/HumanCellAtlas/sctools/pull/50
- https://github.com/HumanCellAtlas/sctools/pull/49

**Comment by rexwangcc** [comment]
All PRs have been merged!
