### ISSUE TITLE
Convert Lira Deployment Job to GitLab deployment job

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#384]
Convert the existing Lira Deployment job to a GitLab deployment job.

**Comment by rhiananthony** [comment]
Tasks which were involved in this effort:
1) Combine the 3 Jenkins jobs into one and get them to run on GitLab
2) Create a config.ctmpl file which is rendered as part of the deployment depending on the environment (The old method contained variables which were injected by Jenkins during deployment).
3) Update the Gitlab runner Docker image with needed libraries for certbot, kubernetes and aws
4) Debug why Alpine linux was behaving differently than the ubuntu image which was originally being used to deploy the tls cert.

**Comment by kbergin** [comment]
Can I get an update here? Would love to close this this week!
