### ISSUE TITLE
Fixes to SS2 zarr conversion

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/secondary-analysis#386]
In HumanCellAtlas/skylab#133, we added a task that converted the RSEM outputs of the SS2 pipeline into a zarr store. There was an interest in getting zarr conversion into the DCP-wide scale tests as quickly as possible, so that PR was merged with a couple outstanding problems:

1. The zarr store created by the new task did not match the published spec that downstream tools have coded against.
2. The exercise of writing the zarr store revealed that the spec needs to handle both string and numeric cell metadata.

AC:
Updates to the zarr conversion task and docker image that produce a conformant zarr store with string and numeric cell metadata.

**Comment by mckinsel** [comment]
See HumanCellAtlas/skylab#137

**Comment by kbergin** [comment]
Thank you so much for summarizing this, Marcus!

**Comment by rexwangcc** [comment]
Other PRs related to this ticket:
- https://github.com/HumanCellAtlas/skylab/pull/139
- https://github.com/HumanCellAtlas/skylab/pull/140
