### ISSUE TITLE
Find/choose datasets to compare Cellranger to Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#389]
AC:
- [x] Write information about datasets chosen into report draft
- [x] Put data in a place where we can use it for analysis

**Comment by jishuxu** [comment]
1. PBMC datasets: 10 Genomix datasets
    1. PBMC 4K: hca-dcp-mint-test-data/10x/pbmc4k
    2. PBMC 8k: hca-dcp-mint-test-data/10x/pbmc8k
2. Kidney datasets with replicates
    1. Title:Single cell RNA-Seq of E18.5 developing mouse kidney and human kidney organoids
    2. Type of experiements:Expression profiling by high throughput sequencing
    3. Summary:These files represent single cell RNA-Seq data generated on a 10x Chromium genomics platform from three biological replicates from the embryonic day (E)18.5 developing mouse kidney and three biological replicates of iPSC-derived human kidney organoids differentiated according to our published protocol (Takasato et al., Nature Protocols 2016). When aggregated, the mouse data represents >6000 cells that passed our QC, containing most major cell types known to exist in the developing mouse kidney. The aggregated human organoid data contains of >7000 cells that passed our QC and contains populations representing endothelial cells, podocytes, stroma, nephron, and off-target populations with similarity to neurons.
    4. GEO link: https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE108291
    5. SRA RUN: https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA428938&go=go
    6. Bucket: gs://hca-dcp-mint-test-data/10x/kidney/human-organoid

**Comment by kbergin** [comment]
Thank you @jishuxu ! Will you please email the AWG with the choices we have for benchmarking and get their thumbs up ?

**Comment by kbergin** [comment]
Also would you mind throwing an estimate on this? remember it's fibonacci voting now :)
