### ISSUE TITLE
Update pull request templates

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#395]
When opening PRs, the description is auto-populated from a template in skylab, lira and pipeline-tools. As a follow-up to a team discussion about PR reviews and testing, update this template to include the following sections:
- Purpose: What is the issue being fixed? Include a link to the ticket.
- Changes: What changes were made to address this?
- Testing: How should a reviewer test/verify these changes? 

ACs:
Update the PR templates for skylab, lira and pipeline-tools:
- [x]  https://github.com/HumanCellAtlas/skylab/blob/master/pull_request_template.md
- [x]  https://github.com/HumanCellAtlas/pipeline-tools/blob/master/pull_request_template.md
- [x]  https://github.com/HumanCellAtlas/lira/blob/master/pull_request_template.md

Add PR templates to 
- [x] `secondary-analysis` , 
- [x] `sctools`, and 
- [x] `cromwell-tools` as well

Consider that in sctools and skylab we may have different templates than in the other repos.

**Comment by kbergin** [comment]
On skylab - please include a checklist item to let Jodi know when there is documentation updates needed (user facing)
