### ISSUE TITLE
[SPIKE][RFC] Long-term plan for "Rerunning a workflow should create a new version of the results bundle"

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#397]
In the long-term, we want the re-analysis workflows to generate a new version of the existing result bundles instead of generating another brand-new bundle. This requires collaboration between Purple and Green:
- @rexwangcc  volunteers from Green
- @justincc  from the Purple

This should be prioritized over the CBeta Process, and should follow the DCP-RFC process.

AC:
- RFC for this topic

**Comment by justincc** [comment]
Extremely primitive RFC started [here](https://docs.google.com/document/d/1XeAw05RAJe20Q1XDF7eLWLGF3gCme4-8l-ZfhtDWOLg/edit)

**Comment by kbergin** [comment]
@rexwangcc I can see there has been some work done on this so I've moved it to to-do, let me know if that's not appropriate.

**Comment by kbergin** [comment]
Hi @rexwangcc @justincc any chance we'll get this into RFC format tomorrow so we can close this ticket in this sprint?

**Comment by rexwangcc** [comment]
I will focus on making the PR to day

**Comment by rexwangcc** [comment]
In the most recent DCP Tech Arch meeting, people agreed to split this into 2 topics:
- Define strategy for the propagation of complex bundle structure metadata updates from ingest to datastore
- Define reanalysis bundling strategy

Which means the current RFC doc needs to be further polished and re-organized, with extra help from DSS. Secondary-analysis will focus on the latter one down the road. Since this ticket already reflected what we have done in the last sprint, we're going to close this ticket for now in favor of a new ticket (#480)
