### ISSUE TITLE
Ensure 10xV2 query matches exactly what we can process

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#398]
We haven't revisited the specificity or design of our 10x query outside of responding to schema changes in over a year. The metadata and the types of data we are ingesting has changed and we have learned a lot about what we should and shouldn't be processing. Overall, it is better to be too strict than too loose on what we match with our query, as we can always go back and analyze data later. The query should be our one source of truth on what our pipeline can process.

AC:
- [ ] Update our query to only match what we can process. Work with Kylee and CBs to list out all of these features.

___

Previous info in ticket:

In #396 we observed that the 10xV2 query was matched by the `rsatija` dataset, which is a cell hashing experiment. Tim has highlighted that although 10xV2 was used on this dataset, the dataset also used another experimental assay called cell hashing. When a 10xV2 experiment has other assays with it, we will not want to match that for our queries. We'll need to understand the metadata in this dataset better and revisit our query to not match these samples.

AC:
Our query is updated so cell hashing experiments do not cause the 10xV2 pipeline to run

From Mallory:
> I believe the `rsatija` dataset has `"sequencing_protocol.sequencing_approach.text": "CITE-seq"` and `"sequencing_protocol.sequencing_approach.ontology": "EFO:0009294"` which indicate the dataset uses hashing.

**Comment by kbergin** [comment]
From a conversation in slack today:
Hi all! It looks like we might have our first 10x single nuclei dataset coming as part of this round of data recruitment. If you don’t want this data to trigger the current Optimus pipeline, you might consider updating the subscription to interrogate the `library_preparation_protocol.nucleic_acid_source` field to match “single cell”.


`"nucleic_acid_source": {
"description": "Source cells or organelles from which nucleic acid molecules were collected.",
"type": "string",
"enum": [
"bulk cell",
"single cell",
"single nucleus",
"bulk nuclei",
"mitochondria"
],`

**Comment by samanehsan** [comment]
Here's the PR! https://github.com/HumanCellAtlas/lira/pull/133

**Comment by samanehsan** [comment]
I noticed an error in the `nucleic_acid_source` field that I had added to the 10x test spreadsheet in integration. That change is required for the DCP integration test bundle to match our new query,  so I will wait to create a new subscription until the fix is merged: [HumanCellAtlas/metadata-schema#842](https://github.com/HumanCellAtlas/metadata-schema/pull/842) :octocat:

**Comment by rexwangcc** [comment]
All sound good! :octocat: :octocat:

**Comment by samanehsan** [comment]
I also updated the test bundle that the mintegration tests would use (it will work for our current subscription as well as the new one) https://github.com/HumanCellAtlas/secondary-analysis/pull/556

**Comment by samanehsan** [comment]
This is now deployed to our integration environment!

**Comment by rexwangcc** [comment]
Yay!
