### ISSUE TITLE
[Spike] Benchmarking plan for Optimus MVP

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#400]
To make sure we are all on the same page with producing a benchmarking report for the Optimus MVP, we will make a spike or maybe **outline** the sections for the Optimus benchmarking report.

Examples from SS2 benchmarking:
[Plan for benchmarking tests](https://docs.google.com/document/d/1Ynk2ng5P0IyilBDh-0BfPEhJnPTnvgUrgULdicEgrws/edit#heading=h.bprqz764ilo2)
[First pass of benchmarking report](https://docs.google.com/document/d/1eBO9IeFs8wQkFhyDkngPTPYNKLllsyqZk1ZxRxefBmk/edit)
[Update to benchmarking report](https://docs.google.com/document/d/1zgMoeDkJk3t0rJdnDM7Dts08A6keKhwxfQtuAM8iHVw/edit#heading=h.5goqeu8sor66)
Preferably this time around we will not need to do two report versions for our MVP :)

**Will be shown to AWG** for approval
- [x] Benchmarking plan - which tests, why we're doing each test, which dataset will be used to show that that test is accurate - [doc here](https://docs.google.com/document/d/1U9YyLgoxEm7bGaKlyqSvslXdah4oX0j_nbrBW_-YeF8/edit?ts=5bec3a54#)
- [x] take into consideration the different pairwise comparisons for references i.e. cellranger gencode vs optimus gencode and optimus gencode vs optimus with the same ref as SS2.
- [x] AWG agrees it would test the pipeline sufficiently to call it an MVP
- [ ] Possibly mention as a checklist item in benchmarking proposal that we will monitor disk space, timing, etc while benchmarking
- [ ] Make other tickets to perform the testing and report writing to complete this benchmarking

**Comment by kbergin** [comment]
https://docs.google.com/document/d/1p7z36muc159OP30vPSAuXLqogNrW6kRm0PZeMsROu2A/edit#

**Comment by kbergin** [comment]
@kishorikonwar Are you leading this? I think I recall from Friday standup that you and @barkasn are working on it with @jishuxu . Please do move this into the appropriate column if so!

**Comment by kishorikonwar** [comment]
This is the document we are working one
https://docs.google.com/document/d/1U9YyLgoxEm7bGaKlyqSvslXdah4oX0j_nbrBW_-YeF8/edit?ts=5bec3a54#
