### ISSUE TITLE
Update to Connexion 2.0

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#409]
Trent from DSS shared a news that Connexion(which is the web service framework Lira is using) published v2.0, we are still using v1.4.2. To update to v2, we might have to modify our API YMAL to adapt to the OpenAPI spec. It will be a moderate change to Lira.

@rexwangcc can you comment or edit this description to highlight why we need to move to 2.0? Is it just to stay up to date or are there other reasons for motivation?

AC:
- [ ] We are using Connexion 2.0

**Comment by amarjandu** [comment]
https://app.snyk.io/org/bento007/test/github/b43bf316-762b-4eb4-b514-32bd14aecd2e/master..d53ac642b86c6c53540a2fc1b154459d120d1d79?fromStatus=true&fromGitHubAuth=true&tab=issues

> Connextion 1.5.3 has potential for arbitrary code execution, issue was raised in another non-related PR.

**Comment by rexwangcc** [comment]
PR: https://github.com/HumanCellAtlas/lira/pull/134/files

**Comment by rexwangcc** [comment]
Another PR for this ticket: https://github.com/HumanCellAtlas/secondary-analysis/pull/552

**Comment by rexwangcc** [comment]
Done!
