### ISSUE TITLE
Knowledge transfer for how to benchmark optimus/cellranger

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#416]
Sync with Jishu about how to benchmark optimus/cellranger

- [x] the set of benchmarking documents/reports
- [x] codes used in the benchmarking process
- [x] datasets used in the benchmarking
- [x] code for SS2 benchmarking is merged in

**Comment by kbergin** [comment]
Checklist above is an example, I was showing Kishori how to use checklists in zenhub. @kishorikonwar please update ticket to reflect the work that needs to be done for this ticket
