### ISSUE TITLE
Run HCA bone marrow through 10x and Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#423]
Run these two datasets we want to run for benchmarking through 10x and optimus pipeline

1. HCA bone marrow dataset

ACs:
- [x] Matrices are produced for both 10x and Optimus (gencode full) and cellranger (gencode filtered)
- [x] Outputs in some public cloud location where the team knows where they are
- [x] Save output bams as well
- [x] Spreadsheet to track runs done, including cromwell workflow ids so we can find them later and which reference&annotation pair and pipeline and dataset are used.

Jishu already ran PBMC 4k through Cellranger with ensembl and gencode reference [here](https://drive.google.com/drive/u/0/folders/15xeKWsa7NOAQoWI8LnzA3p8AHai_-8Tt)

Marked as blocked because 10x we want to wait until we compare v2 and v3. We can continue to run Optimus in the mean time. 

Watch out for scope creep with Optimus / 10x bugs - make new tickets if we run into them.

**Comment by barkasn** [comment]
Downloading HCA data for cord blood and bone marrow (format and separation is unclear at this stage) on devbox at /home/nbarkas/storage3/nbarkas. Will then run 1 lane through cellranger and wait for #454 progress to run through Optimus
