### ISSUE TITLE
Update 10xv2 adapters to use metadata library

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#449]
The metadata library helps us stay up to date on the location of metadata in the schema and protects us from some changes. In our 10xV2 adapters we didn't have the metadata library, so we would want to update it to use it. Our 10xv2 adapters will be updated to support Optimus soon as well, and we should take a look at whether we should consolidate code between the two pipeline adapters, if anything needs to be cleaned up, and what can be updated to keep things organized.

AC:
All adapters we use utilize the metadata library

**Comment by kbergin** [comment]
Possible we may want to do the consolidation of optimus/cellranger adapter code during this ticket

From that ticket: 
Instead of repeating the same task to get 10x inputs from the data store, move the task into a separate WDL file that can be re-used in the Optimus and Cellranger pipelines. Additionally, the task to format the inputs for the submission WDL can be generalized to work with either pipeline.

**Comment by rexwangcc** [comment]
Our cellranger adapters and Optimus adapters are already using the `metadata-api` library. Closing this ticket and moving the consolidation AC to https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/282
