### ISSUE TITLE
Replace cromwell-metadata docker images

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#450]
Instead of storing the service account JSON key for cromwell-as-a-service in a private docker image used by the get-metadata task, use gcloud to access the default service account credentials of the VM running the task and generate a bearer token. Scala example here: https://github.com/broadinstitute/cromwell/blob/develop/scripts/docker-dos/dosUrlLocalizer.sc#L82-L83

AC: 
- Update pipeline-tools script for getting analysis workflow metadata to use default account credentials
- Remove cromewll-metadata docker images from gcr

**Comment by samanehsan** [comment]
PRs are blocked until we are using the PAPI v2 backend but are ready for review in the meantime: 
- https://github.com/HumanCellAtlas/pipeline-tools/pull/105
- https://github.com/HumanCellAtlas/lira/pull/116

**Comment by kbergin** [comment]
Was a 21, re-estimated to a 2.

**Comment by samanehsan** [comment]
The PRs are merged, and we can remove the docker images once the change is promoted through the different environments

**Comment by samanehsan** [comment]
Here is another small PR to delete the old docker file now that this change is deployed in all of our environments: https://github.com/HumanCellAtlas/pipeline-tools/pull/119
