### ISSUE TITLE
Review scale test results

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#453]
Only for Monday 11/26 4k scale test

AC:
- [x] Add errors to scale test spreadsheet
- [x] Make tickets for any new errors we need to address
- [x] Papi v2 Errors found in latest scale test are sent to Henry

**Comment by samanehsan** [comment]
@rexwangcc, did you already start working on this? I thought I remember you mentioning that last week

**Comment by samanehsan** [comment]
Thanks for documenting the errors @rexwangcc! I think we can close this ticket now
