### ISSUE TITLE
Optimus inconsistent docker images

### ISSUE THREAD

**Issue by jishuxu** [HumanCellAtlas/secondary-analysis#455]
Previously, we tried to update Optimus to use the most recent version of sctools. There was an error in one task where we were unable to use the new sctools and didn't have time to dig into why it wasn't working, so we left that one task on the old version. Optimus should only use one version of sctools.

In optimus, the task `SplitBamByCellBarcode.wdl` is using `quay.io/humancellatlas/secondary-analysis-sctools:0.1.9` but other tasks in Optimus using `quay.io/humancellatlas/secondary-analysis-sctools:0.2.0`

AC:
- [ ] Update Optimus sctools version
- [ ] Tag and release Optimus

**Comment by samanehsan** [comment]
There are several versions of sctools used in the optimus pipeline (0.1.9, 0.1.10, 0.2.0 and 0.3.0): https://github.com/HumanCellAtlas/skylab/search?q=sctools&unscoped_q=sctools

**Comment by samanehsan** [comment]
@jishuxu can you link the cromwell-workflow that produced the error?

**Comment by samanehsan** [comment]
All of the Optimus tasks passed when using the latest version of sctools (v3.1), except for `CalculateCellMetrics`. The fix for that issue is here: https://github.com/HumanCellAtlas/sctools/pull/56

Once that is merged, we can tag a new release for sctools, use that version in Optimus, and then tag and release Optimus.

**Comment by barkasn** [comment]
@samanehsan just a heads up that the PR that fixes optimus includes some sctools image version changes (based on a newer image for some steps). Might want to check if that version still breaks the pipeline if used in different versions.

I would also be quite interested to know if the pipeline doesn't complete with the different image version of if it produces slightly different output.
