### ISSUE TITLE
Make the WDL style guide more visible to public

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#456]
We created our Mint WDL style guide in a Google Doc a while ago. It will be much better to write up a more visible/formal guidelines based on that, which should be more visible to the public. A good place would be the wiki-page of Skylab. We could also put it in the detailed page of HCA contents, if it's proper.

AC:
1. Migrate the WDL style guide to a better place.

**Comment by kbergin** [comment]
Here is the style guide https://docs.google.com/document/d/17BLso0oR7clqP0QIgsL2CvJmf-PFEVLhzDkggXfda6U/edit#heading=h.a8j2pofhfr
