### ISSUE TITLE
Look into Python linters and Add Lint hooks for our Repos

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#459]
We have applied Google-style docstrings on all of our Python code for a while. To make our life easier, and encourage the code review to focus more on the functionalities rather than code styles, we need to look into python linter tools and furthermore, integrate them into our development process.

AC:
1. Do some research and comparison between Blac, Flake8, Yapf and other linters
2. Integrate the most suitable one into all of our Python repos.

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-427)

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

This is done\! I’m starting to think unito is syncing old tickets…
