### ISSUE TITLE
Comparison of Cellranger V2 and V3 is repeatable

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#460]
As we work in a public setting, we want our testing to be repeatable by the community and for our own needs when we need to run tests again. 

A suggestion for implementation on this from Nick: Generate a docker container that contains the code and data required to do the comparison of V2 and V3 cellranger versions including the output matrices.

Blocked on finishing the comparison and getting any changes from AWG

AC: 
- [ ] the comparison of cellranger v2 and v3 is easy to re-run
- [x] Please put in github and include a readme

**Comment by barkasn** [comment]
I've added the code in branch:  nb-add-v2-v3-report-code under skylab-analysis/analyses/cellranger_compare_v2_v3/

**Comment by kbergin** [comment]
@barkasn does this need a reviewer?

**Comment by barkasn** [comment]
Not yet. I'm back working on this, quite a few things to do to get it to be easy to run. I'm aiming end of week for this and back on #483 next week.

**Comment by barkasn** [comment]
Merged in the master after review. Code is available here:

https://github.com/HumanCellAtlas/skylab-analysis/tree/master/analyses/cellranger_compare_v2_v3
