### ISSUE TITLE
Debug cellranger analysis error in RUN_TSNE stage

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#462]
We have observed intermittent failures in the RUN_TSNE stage of the CellRanger pipeline. Eg. the following Regev-ICA workflows in production due to this error, but passed after we re-ran them: 
- 445264cb-4826-4cfc-95b0-47c90384f556
- 9844f8ce-0e49-4ddc-91fa-987d47eb125d 

[error] Pipestance failed. Error log at:
618fcb7a-1a41-4baf-ab01-d86c0e87ad34/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/SC_RNA_ANALYZER/RUN_TSNE/fork0/split-u00ab00243e/_errors

We are using the "--nosecondary" flag when running cellranger to skip their secondary analysis (includes clustering and visualization), so the pipeline is not actually creating a tsne plot. It still calls all of the secondary analysis functions, but does a dry run so it is unclear why there are intermittent failures in this step.

**Comment by kbergin** [comment]
That's interesting - maybe we should file the bug with cellranger's repo since we don't plan to continue to run it anyways?
