### ISSUE TITLE
Fix parameter in 10x pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#464]
In the 10x cellranger pipeline, we should be sending in the expected number of cells from the data store metadata if that information is available. It is not a required metadata field in the HCA, so if the information is not available, we should not submit that input to cellranger and it will use cellranger's default setting automatically. This parameter is already an optional parameter in our wdl.

The line where we have set a hardcoded cell count is [here](https://github.com/HumanCellAtlas/pipeline-tools/blob/e99bf53c5bc038ebae50ce56d629bef503793f73/adapter_pipelines/cellranger/adapter_example_static.json#L4) and it is used in the adapter wdl. 

The metadata field where we should be getting this information is in `biomaterial` -> `cell suspension`-> `total_estimated_cell_count` dictionary [here](https://dev.data.humancellatlas.org/learn/metadata/metadata-dictionary/biomaterial)

It is urgent that we fix this and then reprocess the production 10x datasets. All 10x datasets are effected by this. In addition, the pe'er dataset has an incorrect value for this metadatum and is being reuploaded. We will want to cancel those workflows until we fix this issue and then re-run them all ourselves.

AC:
- [x] Update to use this metadata information in our pipeline and needs to get released to production
- [ ] Re-run treutlein, ICA, Pe'er, and meyer datasets (when it is available).
- [ ] Coordinate with data store and browser to deprecate old analysis outputs

**Comment by samanehsan** [comment]
PR is here: https://github.com/HumanCellAtlas/pipeline-tools/pull/107
