### ISSUE TITLE
Update matrix spec to handle isoform data and raw counts

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/secondary-analysis#465]
Presently, the matrix output spec has one array called `expression`. For SS2, that contains gene TPM values. But, the matrix service is supposed to allow users to request raw counts and isoform counts when the assay type supports that. So, the spec needs to updated to included multiple arrays for different data types.

**Comment by brianraymor** [comment]
Moved to https://github.com/HumanCellAtlas/matrix-service/issues/166 and assigned the *Goal: Optimus MVP epic.
