### ISSUE TITLE
Write selected bundle metadata into matrix output

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/secondary-analysis#473]
The matrices presented to the matrix service currently include a lot of computed metadata, things like number of reads per cell. These matrices should also include some bundle metadata, things like organism, disease, instrument, etc.

- [ ] Open question whether we want to do this

**Comment by kbergin** [comment]
Hi @mckinsel  - thank you for the feedback. We are observing in the closed beta user interviews that users aren't able to easily find the metadata in our current user journeys. I'd love to talk through this more with you to find out what the best solution is, I'm not sure if we should be duplicating metadata in our outputs as the internal data storage format or if it should be added upon expression matrix request. Want to set up a time in the new year to think through this? We likely won't get to it until Optimus is done if it's on our plate.

**Comment by mckinsel** [comment]
Yep, let's brainstorm a solution in early January. It's something we've known we need to address, and the beta feedback is highlighting it.

**Comment by kbergin** [comment]
@mckinsel it seems like metadata accessibility use case is an open question across the DCP, not only via the matrix service use cases. Perhaps we should participate in those discussions to see how analysis/matrix service fits in and determine the right course of action.

**Comment by kbergin** [comment]
The matrix service is going to do this as part of their ETL, not part of green box.
