### ISSUE TITLE
Review Kishori's test data production scripts

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#474]
@kishorikonwar created some scripts to be able to create test data for 10x pipelines. It needs to be reviewed. For now, we will validate it's scientific validity so that we can use it to generate testing data. We will revisit it for any needed refactoring, commenting, documenting, and final review and incorporation into our HCA repo at another time after Optimus v1 is done. 

Again, the critical thing here is that we are not producing faulty testing data unknowingly. Please review the scientific validity closely.

AC:
Merged PR https://github.com/kishorikonwar/utilities

**Comment by barkasn** [comment]
I need the following to review this:

* example command with expected output, to verify I am running it correctly
* the code needs to be commented (at least the purpose of every function/class and ideally inline)
* there needs to be a command line help (--help option to explain the available parameters)

**Comment by kbergin** [comment]
Hi Nick, 

Those do seem like important pieces to enable review. And per our team agreements, the instructions on how to test something is required for all requests for code review. 

If it will be a lot more work to comment, add help support, and finish reviewing this code I worry that we don't have time before we finish the Optimus work. Nick has said he doesn't need to create synthetic data for any of that work for now, @kishorikonwar, do you need synthetic data for your work? If not, I'd like to wait to complete this until later.

**Comment by kishorikonwar** [comment]
Hi Guys,

We don't need the synthetic data generator now. We have other priorities.

Thanks,
Kishori
