### ISSUE TITLE
Continued effort for Bundle Versioning RFC

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/secondary-analysis#480]
AC:
- [ ] RFC on bundle versioning is published in dcp-community and reviewed
- [ ] After review, tickets are generated for analysis requirements to accomplish this.

**Comment by kbergin** [comment]
@rexwangcc From our convo earlier it sounds like this is blocked on our end. Should we pull it back into the backlog until it is unblocked? Or do you suspect Justin will get to talk to Norman quickly and we will be able to generate this RFC before next Tuesday when the sprint ends?

**Comment by rexwangcc** [comment]
@kbergin I don't think it's possible for us to be unlocked by the end of this sprint :( Moving it back to backlog sounds great to me! I will keep an eye on it! Thanks!

**Comment by rexwangcc** [comment]
Closed by the latest AUDR proposal happening in DCP
