### ISSUE TITLE
Ingest Authentication using token built from Google Service Account credentials

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/secondary-analysis#481]
Hi Greenbox

Ingest will start using the DCP Auth0 account soon. In line with this, you'll need to stop using the current token endpoint (https://danielvaughan.eu.auth0.com/oauth/token) to authenticate with Ingest. You'll need to generate self-issued JWTs using the Google account credentials as described here https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Security/Authentication%20and%20Authorization/Setting%20up%20DCP%20Auth#sample-code

Currently, only the "Create Submission Envelope endpoint" (POST requests to http://api.ingest.staging.data.humancellatlas.org/submissionEnvelopes) is being authenticated. Changes that verifies the self-issued tokens are to be deployed in dev today. 

Target dates for the changes to be deployed in:
integration: 09/01/2019
staging: 16/01/2019
prod: 23/01/2019

Many thanks
Alegria

---

~*Currently Blocked by Ingest needing to finalize server-side changes in order to be able to read and verify the JWTs that we send them*~

## Context
We had the meeting with Ingest and Dss Engineers talking about DCP Authentication, and we agreed to push forward to standardize the authentication across DCP. The Slack channel for the working group is #dcp-auth-work-group 

At the moment, we are getting auth tokens from Auth0 directly via `/oauth/token` API, which has a rate limit of 30r/s, which is not sufficient given our great amount of workflows running in parallel. We agreed to move to another approach that we slef-assign JWT tokens with Google Service Account and include that JWT with our requests to Ingest. Until we move the information to a centralized place like Auth0, Ingest will have to maintain a whitelist of our Service Account Domains(Google Projects) as what DSS is doing right now in order to verify the signed JWTs. Our code for this part is ready but not deployed: https://github.com/HumanCellAtlas/lira/blob/master/scripts/DCPAuthClient.py

## Action Items
In order to let the Adapter WDLs(pipeline-tools) make and sign JWTs from Google Service Account JSON keys, we need to figure out how to let the workflows access to credentials in the runtime. There are several possibilities:
- Like what we did to remove the crednetials private docker image in pipeline-tools, we read the service account from the VM that the workflows are running on dynamically and make the JWT (@samanehsan has the knowledge to do it)
- We create a safe private bucket and put our service account there(treat it as a Vault), give the workflows privileges to read from the bucket and generate JWT in runtime.
- We create another service to generate JWTs every, say 60mins and save it to a bucket and let workflows read JWTs from the bucket.

**We need to get this done by the end of January**

---

AC
- [ ] We no longer use dan's old endpoint for Auth0 and use the new DCP Auth0 method

**Comment by kbergin** [comment]
Hi @aaclan-ebi I copied over your text and tagged you in a ticket that I think we already have for this! Thanks!

**Comment by justincc** [comment]
This became #461

**Comment by kbergin** [comment]
Summary from our conversation:

Here's the summary from today's meeting.

Ingest had already seen the documentation which Trent had written concerning authentication and already implemented AuthN via a signed JWT in the envelope header (though they have not yet implemented AuthZ). The plan is that they will enable authorization via a white list of privileged domains and any service account from these privileged domains will be authorized.

Eventually the plan will be to migrate towards using Fusillade for Authorization and Authentication when it is ready. The mint team will change the client to deliver a signed JWT instead of an Auth0 token.
