### ISSUE TITLE
Inconsistency in the count matrix, cellbarcodes and gene-names dimension 

### ISSUE THREAD

**Issue by kishorikonwar** [HumanCellAtlas/secondary-analysis#482]
###  Brief Description
In some runs of the Optimus code, the dimensions count matrix, cell id, and gene name array are not compatible.  Specifically, the "MergeCountFiles" folder contains three files

a) **sparse_counts.npz**, which is the actual count matrix values in the CSR matrix format: dimension n_cells x n_genes
b) **sparse_counts_rows.npy**, an array of cell barcodes with length n_cells
c) **sparse_counts_cols.npy**, an array of gene names with length n_genes
The lengths n_cells and n_genes in b) and c) are expected to be equal to the dimensions in the file a) but they are not equal in many runs.

AC :
 - [ ] The lengths n_cells and n_genes in b) and c) must be equal to the dimensions of the matrix a) for any successful run of Optimus.

###  Detailed Description:
As per the matrix service specs for the zarr outputs
https://github.com/HumanCellAtlas/skylab/blob/master/docs/matrix_format_spec.md

The following zarr datasets are expected to be created with matching n_cells and n_genes

A) The output a) from above, where the dimension is n_cells x n_genes

**expression** - The expression values themselves. Rows correspond to cells and columns to genes. These must represent "raw" expression values, though the precise definition of those values may vary by experiment type. .....

shape: (n_cells, n_genes)
compressor: Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
chunk shape: (10000, n_genes)
dtype: float32
This is data should correspond to the output a) from above and 

B) The output b) from above, where the dimension is n_cells

**cell_id** - Identifiers for each cell. The means of identifying a cell varies by experiment type. For example, in droplet data this is a barcode; in well-based assays it could be a well or cell suspension identifier. The ith element of this array identifies the ith row of the expression array. Elements in this array must be unique.

shape: (n_cells,)
compressor: Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
chunk shape: (10000,)
dtype: U40

C) The output c) from above, where the dimension is n_genes

**gene_id** -- Identifiers for each gene. 
The ith element of this array identifies the gene at the ith column of the expression array. The gene_id array must be identical for all expression data produced by HCA secondary analysis pipelines. Elements in this array must be unique.

shape: (n_genes,)
compressor: Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
chunk shape: (n_genes,)
dtype: U40

**Comment by barkasn** [comment]
I checked how the utility that I wrote to read Optimus output behaves when the matrix has this problem. The utility breaks when it encounters the mismatch. This means that previously run datasets (that loaded ok), did not have this problem. I also added a specific check to report this kind of problem in the future in the npz2rds utility.

**Comment by kbergin** [comment]
@barkasn were you running the utility on the zarr outputs or on the other format of outputs? Just curious. Great find that the bug isn't consistent!

**Comment by barkasn** [comment]
@kbergin npz2rds runs on the pre-zarr output (.npy and .npz, numpy files)

**Comment by kbergin** [comment]
Estimate is included in other ticket to transform to zarr

**Comment by kbergin** [comment]
Estimate is regarding the previous effort put into this ticket and the zarr conversion work.
