### ISSUE TITLE
Adding EmptyDrops to Optimus Pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#483]
Partioning and removing barcodes that result from technical artifacts, like ambient contamination or other error processes, from barcodes that build libraries from cells is a way to improve the outputs of our Optimus pipeline. 

The goal here is to select/include an existing algorithm for this. Emptydrops is a method from Jamboree1 that partitions cells and non-cells. 10x has included a version of this algorithm in their latest cellranger v3 pipeline and based on our report [here](https://docs.google.com/document/d/1mCDS6-LmZl-0VS9KYc1KypFnNQyyb4pbFaaamxMBnLw/edit#) we do see some important differences when including emptydrops in the pipeline.  

Consider talking to John Marioni and 10x Developers to understand implementation of emptydrops in 10x pipeline. 

AC:
- [ ] Implementation detail suggested to add binary column of 0/1 to zarr matrix store regarding empty or not based on the outputs of emptydrops 
- [x] Merged into pipeline
- [ ] Documentation of pipeline is updated, including internal specs, user guides, and readmes
- [x] Update tests for Optimus

**Comment by barkasn** [comment]
I have got emptyDrops (as published by the Marioni lab) working on a test dataset. I have created a wrapper script that will allow calling the emptyDrops function from the WDL file, I am also in the process of putting together a docker container with the suitable environment for running this code. The wrapper script has been checked in https://github.com/HumanCellAtlas/skylab-analysis/tree/nb-add-emptyDropsWrapper/tools/emptyDropsWrapper and is awaiting review. The next step is to add a new task in the WDL.

**Comment by barkasn** [comment]
I've now generated a WDL task and integrated emptyDrops into optimus as the last step. I've successfully run this on a test dataset (HCA BM1). There are accessory scripts from skylab-analysis used at the moment, that need to be reviewed further and merged into skylab.

**Comment by barkasn** [comment]
Tested with second datasets (pbmc 4k): cromwell-cd9e7bb0-8a8f-4c6c-8b04-3151fe236679

Results look reasonable (~5220 cells marked as true). Some parameter tuning might be required. Probably want to talk to matrix service before that.

**Comment by barkasn** [comment]
Not ready for merging but opened PR

https://github.com/HumanCellAtlas/skylab/pull/154

**Comment by barkasn** [comment]
This is complete and has passed tests. The PR is awaiting review.

**Comment by barkasn** [comment]
The branch has been updated with the master (as the zarr branch was added while work on this was performed). The tests are all passing. I am doing one last run manually (cromwell-0698be00-8713-4940-be08-6e9566fd244d) to check everything is OK before merging.
