### ISSUE TITLE
Integrate emptyDrops output in the Optimus zarr result

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#492]
Our users currently have two ways of interacting with 10x data in the HCA DCP. One way is to download an entire analysis bundle and retrieve all of the outputs from a particular analysis, which would correlate to a single cell suspension. In this method, the previous ticket which incorporated empty drops and includes the entire csv output would be useful for this user. Another way a user can download our data is through the matrix service. The matrix service relies on zarr outputs from our pipeline to filter and concatenate outputs from different analyses to deliver a single matrix to the user based on their custom requests. Only data that appears in the zarr outputs can currently be included in this final delivered matrix. Therefore, any data we want the user to receive from EmptyDrops needs to be included in our zarr outputs. 

Integrate the metadata produced by the emptyDrops step in output into the zarr output of the pipeline. 

TODO:
- [ ] Coordinate with Matrix service to understand which fields should be retained and how the FDR cutoff should be handled. Options (1) include FDRcutoff during ingest [not preferred] (2) Use default cutoff, that still allows matrix service to override (3) Remove cutoff and leave it to matrix service to specify at delivery time
- [ ] Consider adding compression of the csv between steps
- [ ] Add required columns to zarr metadata, including a binary column if required

AC: 
- [ ] Empty drops output is available via the matrix service (is in zarr format)
- [ ] EmptyDrops information is in a format that can be filtered by matrix service if this is desirable (could be in a future ticket if we want user feedback first)
- [ ] Update documentation (coordinate with Jodi to update the user facing documentation on outputs from pipeline, and ask Matrix service who does their documentation and coordinate)

**Comment by kbergin** [comment]
@mckinsel @brianraymor We'll be pulling this into next sprint starting tomorrow, will have some questions for you.
