### ISSUE TITLE
SS2 Zarr formatted outputs are optional

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#502]
As a user of the SmartSeq2 Pipeline, I may or may not be interested in the zarr formatted outputs that we produce for the HCA DCP. Thus, this conversion should be optional.

AC:
- [x] Zarr conversion is optional step. It is ok if it is on by default, if that makes implementation easier.
- [x] Pipeline is tagged and released in to production
- [x] Please ensure a brief description of what the zarr output is and why someone may want to use it is somewhere in the code (I didn't elaborate the docs in the code at the moment, we might want to work with CBs to add a set of docs to the pipeline later)

**Comment by rexwangcc** [comment]
PR:
- https://github.com/HumanCellAtlas/pipeline-tools/pull/115
- https://github.com/HumanCellAtlas/skylab/pull/155

**Comment by rexwangcc** [comment]
Done, tagged a new release `"SmartSeq2 v2.2.0"`
