### ISSUE TITLE
Recording output data provenance

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/secondary-analysis#507]
Users may send files from the DCP to other users. In this case, there is no guarantee that they will send the provenance metadata with the main data files. This will likely result in situations where users cannot determine how a file was created. We could solve this problem by embedding provenance information in our files directly.

Some of our file formats (BAM) have standardized ways to accomplish this. Others could be easily modified to include provenance information (hdf5, zarr, txt, csv). Some files are impossible to include this information in (fastq, ugh, we should use unaligned bam!)

Do we want to go this route? If so it would require:

Deciding what information from analysis.json needs to be ported to individual files
For each file type, decide how to store such information.
Modify our pipelines/tasks to store this information.

┆Issue is synchronized with this [Jira Bug](https://broadinstitute.atlassian.net/browse/GL-543)

**Comment by kbergin** [comment]
I think this is not the same but has some similarities with this ticket [473](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/473) and I want to tread lightly on including the right information but not duplicating too much of the metadata. I think the tickets came from different user needs. One is thinking of the user directly being able to figure out what a data file is and how it was made, and another is stemming from the metadata not being easy to digest into the matrix service/for users to use. I want to make sure we are putting metadata into files for the right reasons, and not band-aid-ing other things in the system that we should instead just fix. 

Thanks for the ticket!

**Comment by ambrosejcarr** [comment]
> tread lightly on including the right information but not duplicating too much of the metadata

The answer here, I think, is to make sure it's clear (1) where each file's metadata lives (no need to duplicate metadata, requires that we guarantee that the DCP metadata exist in one place, _forever_) and (2) what was done to the file to transform it into its current form. 

I'm not a huge fan of _analysis_ metadata living separately from the data files due to the "forever" requirement above, and since if you're going to put the effort in to make a header in the analysis format that can contain a link to the metadata, you may as well just write in the steps that were applied to the data to close the loop. 

In either case, it feels like the basic requirement is "headers that can contain links to metadata or metadata itself"

**Comment by kbergin** [comment]
Yes I'd agree I think those rules of thumb could help guide us here. Looking forward to diving into it more at the F2F!
