### ISSUE TITLE
[Optimus Report] Outline existing pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#509]
## Part 1: Description of the pipeline
The aim of this section is to provide an authoritative and in sync with current code outline of the steps in the pipeline and justify the choices of tools made referencing relevant documentation. An accompanying appendix (possibly a table, should list the inputs and outputs of every step and have the name of the wdl files and steps that implement it)

### References
Relevant existing documentation:
* [Optimus Strategizing](https://docs.google.com/document/d/1OOkpz5HtphvOe12DIb0ejLT3KNx3cnv5IV8wF9BNk5I)
* [Optimus documentation - DEVELOP](https://docs.google.com/document/d/1KxbOY15Ugq4ZdcSu8GQv9Flr-16UpBuyU_2hLVcq5fs)
* [Design Specification v2 Optimus](https://docs.google.com/document/d/12TutsWTYkc9wAJar-16lJveQ4CXMh5nwL0C8DaG3A4E)

## AC:
- [ ] This section of report is drafted and reviewed, will be finalized in final review of entire report.

**Comment by barkasn** [comment]
I have completed a first draft of the section and moved technical details to supplementary. I am waiting feedback on this section before reviewing current documentation available and utilizing any figures that may be useful.
