### ISSUE TITLE
[Optimus Acceptance Report] The 3' Assay and Computational Challenges

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#516]
[Useful resource](https://docs.google.com/presentation/d/1o7Mp2P1G5php3vlt2VMXqR_CtDYFRALIsOtR9L6q6kk/edit#slide=id.g2fbb04b852_0_12)

[Working Document](https://docs.google.com/document/d/158ba_xQM9AYyu8VcLWsIvSoEYps6PQhgddTr9H0BFmY/edit?ts=5c3f5d65#heading=h.calfpviouwbg)

AC:
- [ ] Complete section 1 of the optimus acceptance report "The 3' Assay and Computational Challenges"
- [ ] Describe the library generation process with special attention to the resulting read structure. Explain what the purpose of the UMI and cell barcode are
- [ ] Survey the literature perform a survey of the tools available for the still changing problems (this should include UMI and cell barcode correction, but may include other things). Summarize competing methodologies
- [ ] State currently known data processing limitations and which points are addressable by currently available methodologies

**Comment by kbergin** [comment]
[This presentation](https://docs.google.com/presentation/d/1o7Mp2P1G5php3vlt2VMXqR_CtDYFRALIsOtR9L6q6kk/edit#slide=id.g2fbb04b852_0_12) that @ambrosejcarr gave on computational challenges for 3' data may be helpful for this ticket @barkasn @kishorikonwar

**Comment by barkasn** [comment]
I've generated the outline of part 1, including two tables with a review of the available tools and have requested feedback before proceeding.

**Comment by kishorikonwar** [comment]
I would be happy to go through it. Could you post the link to the document here?

**Comment by kishorikonwar** [comment]
The zUMI paper  has a nice table listing various tools for UMI and CB correction. Also, zUMI corrects CB.

**Comment by jodihir** [comment]
I think this document reads well and meets the four objectives listed above. I've made some comments to address and can read it again at that point.

**Comment by barkasn** [comment]
I've addressed Jodi's comments and this ticket is ready to be closed. I have asked for some final comments from Tim and Kylee. I will wait until the end of day, address any feedback and close the ticket.
