### ISSUE TITLE
Handle inconsistent Cromwell timestamps

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#523]
The analysis process schema requires the task.start_time and task.stop_time fields to be in the JSON date-time format (e.g. "2019-01-28T10:00:00.000Z"): http://schema.integration.data.humancellatlas.org/type/process/analysis/8.0.3/analysis_process

However, there is an issue in Cromwell with inconsistent timestamps: https://github.com/broadinstitute/cromwell/issues/2743

Since we are currently using the timestamps directly from the Cromwell metadata, this can cause validation issues. Here is an example invalid submission envelope: https://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5c4ee939d3ed1d000774e744/processes

As a result, when constructing the analysis process JSON, we need to ensure that the timestamps are in the correct format. Rex mentioned that the python library "arrow" may make it easier to do this but we can also look at using the standard datetime library.

AC:
- [ ] We are confident that our timestamps meet the schema validation

**Comment by kbergin** [comment]
From refinement, @samanehsan is going to ping Cromwell on the bug one more time before Kylee attempts to raise with product and after that we will prioritize this ticket.

**Comment by kbergin** [comment]
Ruchi says that Bec had to handle this logic for job manager so we can follow up with her for ideas if we want. They won't be able to prioritize fixing this bug right now so I can move this further up our backlog if we want to handle it on our end.

**Comment by samanehsan** [comment]
Here's the PR: https://github.com/HumanCellAtlas/pipeline-tools/pull/117
