### ISSUE TITLE
Replace SortAndCorrectUmiMarkDuplicates with umi-tools

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#524]
The aim of the PR is to replace the currently used step for duplicate removal (SortAndCorrectUmiMarkDuplicates) with umi-tools as this will improve run time and is an approach more suitable to single-cell datasets

TODO:
- [x] Replace SortAndCorrectUmiMarkDuplicates with umi-tools
- [x] Check if sorting is still required downstream? If so, split into a separate step, the task WDL exists
- [ ] Confirm that the tag used is the one that is used downstream in the counting step

AC:
- [x] umi-tools has replaced SortAndCorrectUmiMarkDuplicates
- [x] manual confirmation that UMI correction is working ( check at least 1 locus on IGV )
- [x] Make sure monitoring script is turned on when running data through to test this change; cursory confirmation that we are not making things worse time-wise.

**Comment by barkasn** [comment]
I have added the new steps for umi correction in the nb-add-umitools branch of skylab. In terms of plumbing it seems to run fine. See run 25319977-3f49-4c40-aa1b-9c4948d9b276, but I now need to verify that the tags are correctly added and used downstream as well as that the option that I have used are the optimal for scRNA-seq.

**Comment by kbergin** [comment]
That's a great implementation decision, Nick. Perhaps file a ticket for updating that task to allow that optional parameter in the future if you prefer.

**Comment by barkasn** [comment]
In the past couple of days I've been checking the input and output of umi-tools to confirm it is correct. I found that approximately 500k reads were missing from the output of this step. After some investigation, I found that these were reads with out CB tags and reads without alignments. Although we don't need these reads downstream, third party users might want to get them, in which case we may have to provide them as a separate file.

Otherwise I found that the umi-correction works as expected and I have confirmed with the relevant vignettes that the flags used are correct. I will therefore proceed to work on the code so that tests can pass and it can be merged. Afterwards, we may want to make sure that these reads are retained in a different file.

**Comment by barkasn** [comment]
I have fixed the above issue and performed a new run (still running): 6af4a56f-de13-4161-a3b3-abf71cefa56a

This should fully correct the problem. I will double check the output and the PR is ready for merging after

**Comment by kbergin** [comment]
@barkasn could this be put into review and code-reviewed while that bug is fixed by any chance? Or perhaps it already has been reviewed :)

**Comment by barkasn** [comment]
@kbergin I want to leave it here until the blocker is resolved and I have re-run the pipeline once with this
