### ISSUE TITLE
Add a test in skylab for Optimus that includes the entire PBMC 4k dataset

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#530]
Add a test with the entire PBMC 4k dataset to Optimus. This test should be triggered manually.

Liase with @barkasn as I have the scripts/data locations required ready

ACs:
- [ ] Add a test to optimus with entire PBMC 4k dataset
- [ ] Ensure the test is easy to update with different datasets as we will be adding more in the future
- [ ] Ensure compatibility with dependency list from ticket #527
- [ ] Ensure the test can be triggered automatically under certain conditions by Jenkins (e.g. when pulling into master)

**Comment by kbergin** [comment]
@barkasn I think #527 is not the ticket you meant to link above
