### ISSUE TITLE
[Spike] How is barcode correction done?

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#531]
We need to know exactly how barcode correction is done in the case were an incorrect barcode is equidistant to two correct ones. Specifically we need to know if the abundance of the two whitelisted barcodes can affect the outcome of the correction decision. If so, the pipeline structure needs to be changed to use the entire input dataset in the correction step.

AC:
- [ ] Find out and document in this ticket and the report how the barcode correction is done with attention to barcode correction is done in the case were an incorrect barcode is equidistant to two correct ones
- [ ] If the abundance of the whitelisted barcodes in the rest of the sample affect the decision, make ticket to refactor the pipeline by merging the input fastqs as the first step

**Comment by kbergin** [comment]
@barkasn do you mean umi barcodes or cell barcodes here?

**Comment by barkasn** [comment]
This ticket is no longer relevant as the CB part has been clearly defined as I was preparing for presenting the steps of optimus and the UMI part is about to be replaced.

@kbergin please close
