### ISSUE TITLE
Cromwell-tools jobs fail if dependencies submitted as zip

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#541]
cromwell-tools submit will submit jobs fine if the dependencies provided as a .zip file, but the jobs will then fail early in cromwell with an error that the the first task.wdl is not found.

* An example of this can be found in:  b9b3c032-483d-4f57-b9f3-8616c76d6451
* I have so far verified that the same zip can be submitted OK via the API.
* Both @samanehsan and @rexwangcc can reproduce this.
* Also the same script works fine if the dependencies are submitted as individual files.
* I (@barkasn ) have a file to reproduce this problem (that due to being a tar can't be uploaded here)

**Comment by rexwangcc** [comment]
PR: https://github.com/broadinstitute/cromwell-tools/pull/61

**Comment by rexwangcc** [comment]
Fixed and published on PypI
