### ISSUE TITLE
Pipeline: Optimus supports 10XV3 Chemistry

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#591]
### Objective: As a user with a pipette, I would like the DCP to process 10x v3 data so that I can submit such data to the DCP and view the results in the data store, matrix service and data browser. 

* This issue does not deal with datasets generated using feature barcodes, an optional add-on to 10x v3 chemistry

### Acceptance criteria: 
- Data Analysis Service pipeline tested on bundle generated from 10x v3 data
- Data Analysis Service pipeline *matches* results from Cell Ranger 3.0 when conditioned on Cell Ranger's cell selections, for every tested dataset.
- Data Analysis Service pipeline runs in the DCP production environment, and a test dataset (see below) populates the data store, data browser, and matrix service. 

### "Matches" is defined as: 
- no more than 0.5% deviation in absolute difference between count matrices
- no more than 5% deviation in difference between genes summed across cells that have more than 10 counts
- no drop-out of any gene summed across cells that accrues more than 5 counts. 

### Datasets to test: 
- At least 2 of: https://support.10xgenomics.com/single-cell-gene-expression/datasets
- If datasets are received from HCA contributors, those datasets can be substituted for these datasets.

**Comment by ambrosejcarr** [comment]
I've updated the objective and requirements for this work as requested. I believe it needs sizing, a milestone, and a DCP PO assignment. 

Given the suggestion that the DCP should accept 10x v2 and v3 cell and nuclei data in advance of the HCA Science meeting on October 10, I have scoped this issue criteria accordingly.

**Comment by ambrosejcarr** [comment]
I believe it would be prudent to better understand the differences between 10x v3 and 10x v3.1 chemistries as part of this work. Questions that should be addressed include whether analysis pipelines built for v3.0 chemistry work on v3.1. See legal proceedings between Bio Rad and 10x Genomics for more background. 

v3.1 data: https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.1.0/5k_pbmc_protein_v3_nextgem
