### ISSUE TITLE
Optimus should output gene ids, not gene names

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/secondary-analysis#619]
In the optimus zarr output, the `gene_id` array contains gene names. The other pipelines use gene ids, which is what the matrix service is expecting. Also, gene ids are unique whereas i think the gene names may not be.

The name vs id seems to come from the `GE` tag created with the `TagReadWithGeneExon` tool from dropseqtools.

**Comment by brianraymor** [comment]
@kishorikonwar - calling your attention to this issue that's blocking a Q2 epic.

**Comment by barkasn** [comment]
@mckinsel Thanks for bringing this to our attention!

**Comment by mckinsel** [comment]
@barkasn yeah it's probably best if you have the versions in there, though tbh the matrix service currently ignores them based on the assumption that the gencode versions are kept in sync.

**Comment by kbergin** [comment]
Thanks @mckinsel! Will see this gets prioritized. Does this block the matrix service being able to handle Optimus outputs?

**Comment by mckinsel** [comment]
Yes it's currently blocking our loading of optimus bundles.

**Comment by kbergin** [comment]
Update on progress: @kishorikonwar  is working on a PR to update Optimus to output gene ids in addition to gene names. Infrastructure is aware of the incoming update and will be prepared to create a new integration test bundle for both human and mouse when the update is released. Kishori will put the PR here soon and we will get it reviewed on Monday.

cc @jkaneria @brianraymor
