### ISSUE TITLE
Optimus 1.3.0 - `CreateSparseCountMatrix` running out of disk space

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/secondary-analysis#627]
After the upgrade to Optimus 1.3.0, we are running into integration test failures. These appear to be due to the manner in which the Optimus change for 1.3.0 was implemented - that is instead of one file being used there is an in and an out file which doubles the size required for processing. 

Here is the link for the error log:
https://00e9e64bacb6c2da4cab7f6a6081053c7598dfb57356a7282f-apidata.googleusercontent.com/download/storage/v1/b/broad-dsde-mint-test-cromwell-execution/o/caas-cromwell-executions%2FAdapterOptimus%2F205b446d-4cb2-41fb-a50e-576120d49dd5%2Fcall-analysis%2FOptimus.Optimus%2F5d759fb8-be0e-4e24-b371-3b137c82e66d%2Fcall-CreateSparseCountMatrix%2Fshard-0%2FCreateSparseCountMatrix-0.log?qk=AD5uMEuJg9WWqvKACiu2fjyIqZY2RwEI_1GiQ4fSMSwnZoiZvnUuCziXBltUTcsU-xewRMQqVWo9AbzLmEI_ljt-jhyVaHKdchcOeVQv9RKEA3hk_NY5w957vfgHwLaiJUgBFnmLSW_K0_Plk3M6aYeFlCUYijAZMvOXxfplcYpwwfWfgoOE5MU9wvZymCUypien-ey8oGf4CFVbji4nHLFbdh4SGsOVv7yJD719N7lIRuGQ_os_7_gTcSXGEW91G-Afqt2XFuRSHZYXK4E-NnXPUYHpqtLbBWY-CQOwTp39K1FW4XNa2e5iP2oXRU-6ZjgH1en2nF-aGi_GTX8N6ZFm_30o6ss0FEimrZE_JCJrLwAqcN7ZwnD3SNAg-Mf83BGf6WQnzku4ugG0-dIRV3O9GMN6rbFs5tmscveUKcEJ0ABBSvyuB8KFIwqdY0GBq__JowE7dDSbJu2N7qIndxcsbmgLj_qHvbGV4kh0fhHPVVccnEz97Y0y18xWrHqPsB7BSu_id0ka7XhuiHYXyOn-djHCBJ2OYW78ncNizUwkGQtwQRLRNHBf3CqhlCNHd2avgJVpphirrn4sXRFILjknjFzwJw4XjB34KYSYUY1g_MXFyiiBkJhSUStuALZlTFdOSAmtpS6di6HsN2ivq4qgmX5bHGk9RxTv74Lyk4iATQ1khkyoFR5W3mVU6p5-5NZ1cqi_JtwzP0hOpnrmUmxquBxmxG_FXnlaHDbFA0CJiM-M_zQYRb7kANW7CDpg87E9R_CwXdK8o33orOZpSgb_R-bQC7ZfNGPtCMvpPUsyn5fgbiS8bfVVEJBUPPBijUQdehpQPJafJzHMUEektVvDCZMUbNtLzSp2Yg1YAiwj_rO3j8xOs98M0AOY57Y-2qbhl-eSEKI9BolywFLvn5ew11y3cA3MSKJCMD0tDlOeZF-coQUfkU-MYJvi4NxU6M6_9auZd_dqicjjMSuPburIbxRbcWTIjrStg04jfK_kgMC8J4IfGwW2QgPX5yWm2Aq71SujAHP2WeXHsmXVUHYky3-2c03go9ibaJf1JECMdLdhrgD12udd_rNGPSa9OsjFXfmKGEFd

And we believe that this is the breaking line:
https://github.com/HumanCellAtlas/skylab/blob/5e5e2b89353a09ef6709434eb85a54870dc561ac/library/tasks/CreateCountMatrix.wdl#L63
library/tasks/CreateCountMatrix.wdl:63
```Int disk = ceil((size(bam_input, "Gi") + size(gtf_file, "Gi")) * 4.0) + 1```

**Comment by kbergin** [comment]
All work has been merged for this issue, and Optimus will be ready for release in the morning.

**Comment by kbergin** [comment]
Optimus 1.3.1 released with a fix today.
