### ISSUE TITLE
Use token to access PUT/PATCH/POST to ingest endpoints

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/secondary-analysis#629]
Ingest implemented this for security reasons. Analysis aren't currently doing this. Ingest temporarily rolled this requirement back. Please implement asap since this is necessary for ingest to secure our systems. See https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/452

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-455)

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

This ticket is done\!
