### ISSUE TITLE
Does the Matrix service have what it needs to serve mouse matrices

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#641]
Create a test analysis bundle in integration env for Matrix Service testing. For Mouse Smartseq2. Share this bundle with Marcus Kinsella at CZI via email or HCA slack to see if the matrix service needs anything else to be able to run mouse data.

If they don’t need anything, ask for feedback on mouse analysis outputs for Optimus and SS2. 

**Why?** The Matrix service may need more information, or changes to the mouse data outputs

**Where to start?** Talk to Nick/Kishori, and reach out to Marcus via Slack. Check if there is SS2 mouse example output bundles in a DCP environment. Work with Lantern to create them if there is not, it can be done before validation is complete, as long as it’s known it cannot be merged into Prod until it is validated].

**When is it done?** When the matrix service can support mouse data outputs, or when we have a list of task needed to complete matrix service support.

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-357)

**Comment by kbergin** [comment]
➤ Charles Yan commented:

I think we’ll need to run ss2 on mouse inputs to create an analysis bundle for this. To do this we’ll need an ss2 mouse input bundle and mouse references for ss2.

**Comment by kbergin** [comment]
I was under the impression that Hornet already had the mouse references because [~accountid:5b43ab1e441e440653b0a4d9] had said that SS2 mouse was ready to go on the Hornet side as soon as we had validated. Let us know if you need reference info from us, though. Thanks Charley\!

If you reach out in the wranglers channel on HCA slack you can probably find someone who can point you to a mouse primary bundle.

**Comment by kbergin** [comment]
➤ Charles Yan commented:

The infrastructure changes that came in after the pipeline surge set us up to be a step away from running mouse bundles for ss2, but not quite there. The outstanding steps are to trivially drop-in the mouse references and to modify lira’s subscription query for ss2 to include mouse bundles. I got the references from Kishori earlier today and have added them on a branch. I will merge that up once I’ve successfully run a mouse bundle through the pipeline.

**Comment by kbergin** [comment]
➤ Chengchen Wang commented:

The workflow failed at the submission: https://job-manager.caas-prod.broadinstitute.org/jobs/2106c2aa-e31a-4654-a289-d6b5dde3a356 ( https://job-manager.caas-prod.broadinstitute.org/jobs/2106c2aa-e31a-4654-a289-d6b5dde3a356 )

It seems the lira config for launching the workflow is a bit messed up, by using integration everywhere should work\!

**Comment by kbergin** [comment]
From Charley: We’ve prepared an SS2 mouse bundle in integration for matrix service testing. Please let me know if there are any issues with the bundle or anything else you need!

```analysis bundle uuid    51d8eda8-bbd9-48ab-9ffc-00cf1cdef087
analysis bundle version 2019-08-05T141528.848170Z
primary bundle uuid     c6cb322a-3d63-4a0b-8440-533da4febc63
primary bundle version  2019-08-02T202139.757537Z```

**Comment by kbergin** [comment]
➤ Charles Yan commented:

We’ve prepared an analysis bundle in integration now:
analysis bundle uuid    51d8eda8-bbd9-48ab-9ffc-00cf1cdef087
analysis bundle version 2019-08-05T141528.848170Z
primary bundle uuid     c6cb322a-3d63-4a0b-8440-533da4febc63
primary bundle version  2019-08-02T202139.757537Z

**Comment by kbergin** [comment]
@mckinsel @brianraymor @jkaneria has matrix service had the chance to validate these bundles?

**Comment by brianraymor** [comment]
From my conversation with @mckinsel yesterday, the bundles were _a-ok_ and our implementation is proceeding.

**Comment by samanehsan** [comment]
In that case, is it okay to close this ticket @kbergin?

**Comment by mckinsel** [comment]
fyi, we've closed the related ticket in the matrix service repo: HumanCellAtlas/matrix-service#279

**Comment by samanehsan** [comment]
Awesome! Thanks for the update @mckinsel!
