### ISSUE TITLE
Add support for SS2 Mouse

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#674]
The required info should be here: [https://broadinstitute.slack.com/archives/CESEYJW9W/p1561567069254000](https://broadinstitute.slack.com/archives/CESEYJW9W/p1561567069254000)

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-318)

**Comment by ambrosejcarr** [comment]
The required information is [here](https://docs.google.com/document/d/1Gxp-xclDY_WP7_ffkXVhB-YBxk34oJLlh37ztLb6iT4/edit).

**Comment by kbergin** [comment]
➤ Charles Yan commented:

I think this only involves following completion of this ticket https://broadinstitute.atlassian.net/browse/GH-357 ( https://broadinstitute.atlassian.net/browse/GH-357|smart-link ) and then updating subscription queries to “flip the switch” on ss2 mouse bundles.

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

This PR updates the subscription queries to match mouse or human data:https://github.com/HumanCellAtlas/lira/pull/186 ( https://github.com/HumanCellAtlas/lira/pull/186|smart-link )

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

For QA, send a notification to Lira for a bundle that contains mouse data (preferably in integration) and confirm that it launches an analysis workflow.

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Ok\! Just curious how did you create the bundle if it wasn’t through ingest?
