### ISSUE TITLE
Analyze 10x KidneySingleCellAtlas dataset with Optimus in production

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#784]
Project uuid is abe1a013-af7a-45ed-8c26-f3793c24a1f4 and it should start 47 workflows. Note this project was ingested twice so please ensure this is the one that gets analyzed.

[https://tracker.data.humancellatlas.org/](https://tracker.data.humancellatlas.org/)

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-469)

**Comment by ESapenaVentura** [comment]
I'm the data wrangler for this dataset. Does anyone know what has happened with the analysis? It's saying in the tracker that there are  49 workflows, 3 of which have failed. I have no access to the job manager, so this is all I know. 

If anyone could please give me an indication of what's happening, that would be lovely. Thanks!

**Comment by ESapenaVentura** [comment]
Thanks @samanehsan! I didn't know it, that is nice to know :)

Also, @mshadbolt ^^ We should get set up with the job manager

**Comment by ESapenaVentura** [comment]
Hi @samanehsan! Is there any plan to submit the last workflow soon?

**Comment by samanehsan** [comment]
@ESapenaVentura we just re-submitted it with a change that should log more detailed info to help us with debugging, since it was unclear to us why it was failing: https://job-manager.caas-prod.broadinstitute.org/jobs/f77f6137-2744-47bf-a15f-3ef7a1526165?q=caas-collection-name%3Dlira-prod%26project_shortname%3DKidneySingleCellAtlas

**Comment by samanehsan** [comment]
Oops made a mistake with manually re-running the workflow so I restarted it: https://job-manager.caas-prod.broadinstitute.org/jobs/594d367e-d542-4ff1-bb73-1405de7f45f7?q=caas-collection-name%3Dlira-prod%26project_shortname%3DKidneySingleCellAtlas

**Comment by ESapenaVentura** [comment]
Any news on this?

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Yes, I was able to confirm the failing steps do not have enough memory so I'm going to sync up with our comp bios about this tomorrow\! Apologies for the delay here\!

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

I created a PR to increase the memory for the failing steps here: https://github.com/HumanCellAtlas/skylab/pull/255 ( https://github.com/HumanCellAtlas/skylab/pull/255|smart-link )

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Re-running the workflow with more memory now: https://job-manager.caas-prod.broadinstitute.org/jobs/7c2a4d69-c75c-4d82-bfaa-c9cfb6d682e5?q=caas-collection-name%3Dlira-prod%26project_shortname%3DKidneySingleCellAtlas ( https://job-manager.caas-prod.broadinstitute.org/jobs/7c2a4d69-c75c-4d82-bfaa-c9cfb6d682e5?q=caas-collection-name%3Dlira-prod%26project_shortname%3DKidneySingleCellAtlas )
