### ISSUE TITLE
Analyze 10x v2 retina dataset

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#795]
This dataset is a part of the "Barcelona" incentive and should be analyzed with Optimus ASAP.

Project uuid: 8185730f-4113-40d3-9cc3-929271784c2b

Data tracker includes more info about the project status here: [https://tracker.data.humancellatlas.org/](https://tracker.data.humancellatlas.org/)

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-500)

**Comment by mshadbolt** [comment]
The resubmitted version with correct schema versions and end_bias tag is now ready for analysis 

project uuid: 8185730f-4113-40d3-9cc3-929271784c2b

tracker link: https://tracker.data.humancellatlas.org/?projectUUID=8185730f-4113-40d3-9cc3-929271784c2b

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Workflows are running here: https://job-manager.caas-prod.broadinstitute.org/jobs?q=caas-collection-name%3Dlira-prod%26project_shortname%3DWongAdultRetina ( https://job-manager.caas-prod.broadinstitute.org/jobs?q=caas-collection-name%3Dlira-prod%26project_shortname%3DWongAdultRetina )

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

The workflows succeeded and the analysis bundles are present in both AWS and GCP
