### ISSUE TITLE
Update 10x subscription query

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/secondary-analysis#800]
The current subscription query for 10 x to trigger analysis is set to 

`10x v2 sequencing`

it should be changed to

`10x 3' v2 sequencing`

OR

`10x v2 sequencing`

with

`3 prime tag`

Eventually, the 

`10x v2 sequencing`

with

`3 prime tag`

should be removed from the query as the

`end bias`

field will be deprecated as redundant: [https://github.com/HumanCellAtlas/metadata-schema/issues/1128](https://github.com/HumanCellAtlas/metadata-schema/issues/1128)

This is due to the fact that we have now new more specific ontology terms and the newly ingested datasets will be using the new terms from after the Barcelona incentive (October 11 2019).

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-557)

**Comment by rexwangcc** [comment]
> it should be relaxed to 10x 3' v2 sequencing OR 10x v2 sequencing with 3 prime tag.

I think the `relaxed` is a typo here 🤔 ?

**Comment by zperova** [comment]
good catch @rexwangcc

**Comment by jahilton** [comment]
When possible, can secondary-analysis confirm an expected delivery date?

**Comment by samanehsan** [comment]
Just to confirm, this also applies to `10x v3 sequencing` right? We are planning to update the 10x subscription query to work for either 10x v2 or v3 data so it would be great to know if need to check for either `10x 3' v3 sequencing` or `10x v3 sequencing` with `3 prime tag` as well.

**Comment by jahilton** [comment]
Yes, this applies to 10x v3 as well.
@zperova is it necessary to continue the query for <general term> + <n prime tag>? or can they just switch over to only querying for the specific term?

**Comment by zperova** [comment]
@samanehsan could you please check for both for now:
`10x 3' v3 sequencing` and `10x v3 sequencing` with `3 prime tag` 
`10x 3' v2 sequencing` and `10x v2 sequencing` with `3 prime tag` 
`10x 5' v2 sequencing` and `10x v2 sequencing` with `5 prime tag` 

until we do all the AUDRs

**Comment by samanehsan** [comment]
Thanks @zperova! We do not support 5' sequencing at the moment, so I will update the query to match one of the following conditions:  
- 10x 3' v3 sequencing
- 10x v3 sequencing with 3 prime tag
- 10x 3' v2 sequencing
- 10x v2 sequencing with 3 prime tag

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Here is the PR\! https://github.com/HumanCellAtlas/lira/pull/194 ( https://github.com/HumanCellAtlas/lira/pull/194|smart-link )

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

For QA, I queried the production DSS for the number of bundles that matched each condition individually. Then, I confirmed that the results of the query in the PR was the total of each condition added together.

**Comment by kbergin** [comment]
➤ Chengchen Wang commented:

QAed\!
