### ISSUE TITLE
Analyze 10x v2 SingleCellLiverLandscape Dataset

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/secondary-analysis#810]
Analyze the dataset "Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations" (project uuid: 4d6f6c96-2a83-43d8-8fe1-0f53bffd4674) with Optimus pipeline in production.

**Comment by jychien** [comment]
@HumanCellAtlas/data-ops

**Comment by samanehsan** [comment]
Analysis is running here: https://job-manager.caas-prod.broadinstitute.org/jobs?q=caas-collection-name%3Dlira-prod%26project_uuid%3D4d6f6c96-2a83-43d8-8fe1-0f53bffd4674

**Comment by samanehsan** [comment]
Analysis is complete!
