### ISSUE TITLE
Analyze human 10X V2 dataset: Reprogrammed_Dendritic_Cells 

### ISSUE THREAD

**Issue by jlzamanian** [HumanCellAtlas/secondary-analysis#811]
The Reprogrammed_Dendritic_Cells dataset is ready for secondary analysis.

This is a Barcelona incentive dataset and therefore high priority. @HumanCellAtlas/data-ops 

**Project title:** Single cell profilling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts
**Project short name:** Reprogrammed_Dendritic_Cells
**Project UUID:** 116965f3-f094-4769-9d28-ae675c1b569c
**Metadata:** human, 10X V2
**Bundles:** 3 primary bundles

https://tracker.data.humancellatlas.org/?projectUUID=116965f3-f094-4769-9d28-ae675c1b569c

**Comment by samanehsan** [comment]
Analysis for this dataset is complete!
