### ISSUE TITLE
Analyze mouse 10x v2 dataset: HumanColonicMesenchymeIBD

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/secondary-analysis#816]
The "HumanColonicMesenchymeIBD" mouse bundles were previously run with optimus_v1.3.2  and need to be rerun with optimus_v1.3.5 because v1.3.3 was the one that was approved. 

**Project title**: Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease
**Project short name:** HumanColonicMesenchymeIBD
**Project UUID**: f8aa201c-4ff1-45a4-890e-840d63459ca2
**Metadata:** mouse, 10x v2
**Bundles**: 6 primary bundles

https://humancellatlas.slack.com/archives/C6C5S6B5W/p1570230566137700

https://tracker.data.humancellatlas.org/?projectUUID=f8aa201c-4ff1-45a4-890e-840d63459ca2

@HumanCellAtlas/data-ops

**Comment by samanehsan** [comment]
@jychien since we do not have a way to update existing analysis bundles with new analysis results, we would have to wait until that feature is complete or tombstone the existing analysis bundles.

**Comment by jychien** [comment]
@samanehsan Thanks for the update. From a DataOps perspective, it would make more sense to tombstone the existing analysis bundles rather than to wait for feature development. The earlier we make the "new" analysis bundles available, we decrease the possible numbers of users that will be using the "old" analysis data.

**Comment by kbergin** [comment]
I can confirm tomorrow, but I don’t think any significant changes went in between 1.3.2 and 1.3.3 (hence only the patch version update). The only difference was a memory bump. 1.3.2 did include an important change from the previous release that was part of our validation. 1.3.3 just happened to be released when we got the mouse validation. I will work on us publishing a bit more information about our versioning process, ideally a patch version change should never impact whether something is valid scientifically. 

As long as the mouse reference used in the analysis of this dataset with optimus 1.3.2 is the same as the one we are currently using in production then I would keep the 1.3.2 results and call this done.

**Comment by kbergin** [comment]
Confirming that there was only a memory bump between these two versions.

**Comment by samanehsan** [comment]
Thanks @kbergin! In that case we should keep the current analysis results instead of tombstoning them in production.

**Comment by jychien** [comment]
Thanks @samanehsan and @kbergin! Yes, let's keep the current analysis and close the ticket.
