### ISSUE TITLE
Wipe all data from spatio-temporal kidney project

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/secondary-analysis#820]
We had a project submitted where part of the data is in violation of GDPR. The plan is to wipe the project completely from all components and re-ingest the OK data (w/ new analysis, etc).

The project was submitted to prod, staging, dev, and integration. I'm not sure which would correlate to 2ry Analysis data storage. Prod is considered high priority/ASAP/urgent given it is more known/accessible to users, with other envs important but not urgent.

https://data.humancellatlas.org/explore/projects/abe1a013-af7a-45ed-8c26-f3793c24a1f4
Project uuid: abe1a013-af7a-45ed-8c26-f3793c24a1f4
Project label: KidneySingleCellAtlas

@HumanCellAtlas/data-ops

┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-556)

**Comment by kbergin** [comment]
Rex is working on a script to delete this dataset's intermediate outputs from our execution buckets.

**Comment by rexwangcc** [comment]
Just an update since the sync between our board and github issues stopped working for a while ... I created the script and it will be ready for review in this repo under `operations/data_cleanup` by the end of today!

**Comment by rexwangcc** [comment]
PR: https://github.com/HumanCellAtlas/secondary-analysis/pull/825

**Comment by rexwangcc** [comment]
the progress is done, all data should be erased from the analysis execution buckets, one could verify this by querying the workflows for this project in the Job Manager, and find the `erased` label under the "comment" column!
