### ISSUE TITLE
Design doc for reference masking

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#93]
Jishu suggested it would be a better idea to mask a complete reference internally within the pipeline rather than require the user to provide a masked reference themselves. Ambrose concurs. We should thus design a reference masking and processing scheme for biotype removal that would work with SS2 and 3' pipelines. 

This can be a hard-masking where we remove annotations that are not expected, but we should formalize the way we produce our internal annotations.

AC:
- design doc
- Get Adam Frankish's comments on the draft when ready for review (frankish@ebi.ac.uk)

**Comment by kbergin** [comment]
https://docs.google.com/document/d/16ltrY2UfgJHwMzFZtGKIafP4cU2m_Pa-Z9yQaxzaOrM/edit

**Comment by kbergin** [comment]
Looking for confirmation that the epic on reference masking covers the open comments that need tickets so I can take myself off this review.

Tickets from reference masking doc @ambrosejcarr  @jishuxu  @TimothyTickle are now grouped into this epic: https://app.zenhub.com/workspace/o/humancellatlas/secondary-analysis/issues/241

Please let me know if you feel I've missed any of the action items or comments from the doc.
The order I've intended with the tickets as they are now is #93, #238, #239, #240, #181, #171 / #172

**Comment by ambrosejcarr** [comment]
> Looking for confirmation that the epic on reference masking covers the open comments that need tickets so I can take myself off this review.

Confirmed. @kbergin
