### ISSUE TITLE
Prod!

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#99]
This project doesn't follow our naming scheme, which may complicate things a bit?

Create a production environment that is the same as our current staging env

AC:
- [x] Prod Lira on CaaS
- [x] Prod JMUI on CaaS - deployed with Cromwell
- [x] Uses google project from Sam Pierson with prod funding
- [x] Prod subscriptions are off for now

**Comment by kbergin** [comment]
@rhiananthony I turned the ACs above into a checklist if you want to utilize it!

**Comment by rexwangcc** [comment]
Based on what we have done during the Sept. Eng f2f, I checked off some of the items in the above checklist

**Comment by rexwangcc** [comment]
Our Prod Lira is up and running now
